Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-11, with the labels that each got.

#370 Fixed InjectAViewModel validation
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
Labels: Award: bug fix, Partner: Zilker Technology, Progress: review, partners-contribution

#368 Allow theme override of non-magento composer themes
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: Award: bug fix, Award: category of expertise, Partner: Something Digital, Progress: approved, partners-contribution, requires Backport to patch version

#371 Backport #386 Allow theme override of non-magento composer themes
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: Partner: Something Digital, Progress: review, partners-contribution

#373 Added XML reference for disabled plugins
  src/com/magento/idea/magento2plugin/reference/provider/PluginReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  testData/reference/xml/DisabledPluginReferenceRegistrar/disabledPluginNameMustHaveReference/di.xml
  tests/com/magento/idea/magento2plugin/reference/xml/DisabledPluginReferenceRegistrarTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#376 Removed residue code
  resources/META-INF/plugin.xml
Labels: Award: bug fix, Partner: Zilker Technology, Progress: review, partners-contribution

#378 Adjusted CHANGELOG.md for 2.0.2 patch release
  CHANGELOG.md
Labels: Award: cleanup, Partner: Atwix, Progress: on hold, partners-contribution

#380 2.0.2 >2.1.0 forwardport
  .github/workflows/gradle.yml
  CHANGELOG.md
  resources/META-INF/plugin.xml
  resources/liveTemplates/MagentoPWA.xml
  resources/phpstorm.meta.php/di-autocomplete.php
Labels: Partner: Atwix, partners-contribution

#381 Updated README.md
  README.md
Labels: Award: cleanup, Partner: Zilker Technology, Progress: ready for review, partners-contribution

#382 Inspection warning for disabling of an invalid plugin
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  testData/inspections/xml/PluginDeclarationInspection/disabledNonExistingPlugin/di.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#383 Added file template content for Form button class
  resources/fileTemplates/internal/Magento Php Form Button Block Class.php.html
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#388 Added test for PhpServiceMethodReferenceProvider
  src/com/magento/idea/magento2plugin/reference/provider/PhpServiceMethodReferenceProvider.java
  testData/project/magento2/vendor/magento/module-catalog/Api/ProductRepositoryInterface.php
  testData/reference/xml/WebApiMethodReferenceRegistrar/webApiMethodMustHaveReference/webapi.xml
  testData/reference/xml/WebApiMethodReferenceRegistrar/webApiMethodMustNotHaveReference/webapi.xml
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/WebApiMethodReferenceRegistrarTest.java
Labels: Award: test coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#386 Added test coverage for PhpConstructorArgumentReferenceProvider
  src/com/magento/idea/magento2plugin/reference/xml/PolyVariantReferenceBase.java
  testData/project/magento2/app/code/Foo/Bar/Model/Logger.php
  testData/project/magento2/vendor/magento/framework/Logger/LoggerInterface.php
  testData/project/magento2/vendor/magento/module-backend/Model/Source/YesNo.php
  testData/reference/xml/ConstructorArgumentReferenceRegistrar/diXmlConstructorArgumentMustHaveReference/di.xml
  testData/reference/xml/ConstructorArgumentReferenceRegistrar/diXmlConstructorArgumentMustNotHaveReference/di.xml
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/ConstructorArgumentReferenceRegistrarTest.java
Labels: Award: test coverage, Partner: Zilker Technology, Progress: review, partners-contribution

#387 Issue-288 - Add description to template
  resources/fileTemplates/code/Magento Module UI Component Form Field Xml.xml.html
  resources/fileTemplates/internal/Magento Form Button Block Class.php.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#390 Added test coverage for EventNameReferenceProvider
  src/com/magento/idea/magento2plugin/reference/provider/EventNameReferenceProvider.java
  testData/reference/xml/ObserverReferenceRegistrar/eventNameMustHaveReference/events.xml
  testData/reference/xml/ObserverReferenceRegistrar/eventNameMustNotHaveReference/events.xml
  testData/reference/xml/ObserverReferenceRegistrar/observerInstanceMustHaveReference/events.xml
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/ObserverReferenceRegistrarTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#395 Added test coverage for PhpConstructorArgumentCompletionProvider
  testData/completion/xml/ConstructorArgumentCompletionRegistrar/diXmlMustHaveCompletion/di.xml
  tests/com/magento/idea/magento2plugin/completion/xml/ConstructorArgumentCompletionRegistrarTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#398 Revert "Issue-288 - Add description to template"
  resources/fileTemplates/code/Magento Module UI Component Form Field Xml.xml.html
  resources/fileTemplates/internal/Magento Form Button Block Class.php.html
Labels: Partner: Atwix, Progress: approved, partners-contribution

#396 Added test coverage for PhpClassMemberCompletionProvider
  testData/completion/xml/PhpClassMemberCompletionRegistrar/diXmlMustHaveCompletion/di.xml
  testData/project/magento2/vendor/magento/module-backend/Model/Source/YesNo.php
  tests/com/magento/idea/magento2plugin/completion/xml/PhpClassMemberCompletionRegistrarTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#392 Added generate models action
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Collection Class.php.ft
  resources/fileTemplates/internal/Magento Collection Class.php.html
  resources/fileTemplates/internal/Magento Model Class.php.ft
  resources/fileTemplates/internal/Magento Model Class.php.html
  resources/fileTemplates/internal/Magento Resource Model Class.php.ft
  resources/fileTemplates/internal/Magento Resource Model Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/CollectionData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ResourceModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassGeneratorUtil.java
  src/com/magento/idea/magento2plugin/magento/files/AbstractPhpClass.java
  src/com/magento/idea/magento2plugin/magento/files/CollectionPhp.java
  src/com/magento/idea/magento2plugin/magento/files/FormButtonBlockPhp.java
  src/com/magento/idea/magento2plugin/magento/files/ModelPhp.java
  src/com/magento/idea/magento2plugin/magento/files/ResourceModelPhp.java
  testData/actions/generation/generator/ModuleCollectionGenerator/generateFile/TestCollection.php
  testData/actions/generation/generator/ModuleModelGenerator/generateFile/TestModel.php
  testData/actions/generation/generator/ModuleResourceModelGenerator/generateFile/TestResourceModel.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGeneratorTest.java
Labels: Award: advanced, Award: test coverage, Partner: Atwix, Progress: review, partners-contribution

#393 Improved tests logic
  src/com/magento/idea/magento2plugin/reference/provider/EventDispatchReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/LayoutBlockReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/LayoutContainerReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/LayoutUpdateReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/PhpClassMemberReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/PhpConstructorArgumentReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/UIComponentReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/VirtualTypeReferenceProvider.java
Labels: Award: category of expertise, Partner: EY, Progress: approved, partners-contribution

#394 Added test coverage for PhpServiceMethodCompletionContributor
  testData/completion/xml/PhpServiceMethodCompletionRegistrar/webApiXmlMustHaveCompletion/webapi.xml
  tests/com/magento/idea/magento2plugin/completion/xml/PhpServiceMethodCompletionRegistrarTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#400 Added QuickFix for missing GraphQL resolver
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/graphqls/SchemaResolverInspection.java
  src/com/magento/idea/magento2plugin/inspections/graphqls/fix/CreateResolverClassQuickFix.java
Labels: Award: bug fix, Award: category of expertise, Partner: EY, Progress: review, partners-contribution

#399 Data model generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Data Model Interface.php.ft
  resources/fileTemplates/internal/Magento Data Model Interface.php.html
  resources/fileTemplates/internal/Magento Data Model.php.ft
  resources/fileTemplates/internal/Magento Data Model.php.html
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DataModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DataModelInterfaceData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/code/ClassPropertyData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassGeneratorUtil.java
  src/com/magento/idea/magento2plugin/magento/files/DataModel.java
  src/com/magento/idea/magento2plugin/magento/files/DataModelInterface.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  testData/actions/generation/generator/DataModelGenerator/generateDataModel/Sample.php
  testData/actions/generation/generator/DataModelInterfaceGenerator/generateDataModelInterface/SampleInterface.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGeneratorTest.java
Labels: Award: advanced, Award: category of expertise, Award: test coverage, Partner: EY, Progress: review, QA passed, partners-contribution

#402 Updated CHANGELOG.md for 2.1.0 release
  CHANGELOG.md
Labels: Partner: EY, Progress: approved, partners-contribution

#401 Added test coverage for PluginInspection
  testData/inspections/php/PluginInspection/withWrongCallableType/Plugin.php
  testData/inspections/php/PluginInspection/withWrongParameterType/Plugin.php
  tests/com/magento/idea/magento2plugin/inspections/php/PluginInspectionTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution
