Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-12, with the labels that each got.

#408 Fixed incorrect file template content
  resources/fileTemplates/internal/Magento Form Button Block Class.php.html
  resources/fileTemplates/internal/Magento UI Component Form XML.xml.html
Labels: Partner: EY, Progress: review, partners-contribution

#404 Added template description for Magento Resource Model Class
  resources/fileTemplates/internal/Magento Resource Model Class.php.html
Labels: Progress: approved

#413 3.0.0 fixed tests, actualised dependencies
  .github/workflows/gradle.yml
  CHANGELOG.md
  build.gradle
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/PhpClassNameIndex.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java.ignore
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGeneratorTest.java.ignore
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorHaveSetupVersionTest.java.ignore
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java.ignore
  tests/com/magento/idea/magento2plugin/linemarker/LinemarkerFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/linemarker/graphqls/GraphQlResolverClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/ConfigurationTypeClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/ObserverClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/PluginLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLinemarkerRegistrarTest.java
Labels: Award: advanced, Award: bug fix, Partner: Atwix, partners-contribution

#415 Fix publishing
  .github/workflows/gradlepublish.yml
  .github/workflows/gradlepublishalpha.yml
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#416 #286 Fixed StringIndexOutOfBoundsException on PluginInspection
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#417 Skip IDEA include tag
  CHANGELOG.md
  README.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/PhpClassNameIndex.java
Labels: Award: advanced, Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#418 3.0.1 ->3.1.0 forwardport
  .github/workflows/gradlepublish.yml
  .github/workflows/gradlepublishalpha.yml
  CHANGELOG.md
  README.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/PhpClassNameIndex.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#407 Covered ObserverDeclarationInspection with tests
  testData/inspections/xml/ObserverDeclarationInspection/observerNameUsedInDifferentFile/events.xml
  testData/inspections/xml/ObserverDeclarationInspection/observerNameUsedInSameFile/events.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspectionTest.java
Labels: Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#411 Queue generator
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Queue Communication XML.xml.ft
  resources/fileTemplates/internal/Magento Queue Communication XML.xml.html
  resources/fileTemplates/internal/Magento Queue Consumer XML.xml.ft
  resources/fileTemplates/internal/Magento Queue Consumer XML.xml.html
  resources/fileTemplates/internal/Magento Queue Publisher XML.xml.ft
  resources/fileTemplates/internal/Magento Queue Publisher XML.xml.html
  resources/fileTemplates/internal/Magento Queue Topology XML.xml.ft
  resources/fileTemplates/internal/Magento Queue Topology XML.xml.html
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/QueueCommunicationData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/QueueConsumerData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/QueuePublisherData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/QueueTopologyData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphaWithDashRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphaWithPeriodRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpClassFqnRule.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueueCommunicationGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueueConsumerGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueuePublisherGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueueTopologyGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCommunicationXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueConsumerXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueuePublisherXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueTopologyXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueXml.java
  src/com/magento/idea/magento2plugin/magento/files/QueueCommunicationXml.java
  src/com/magento/idea/magento2plugin/magento/files/QueueConsumerXml.java
  src/com/magento/idea/magento2plugin/magento/files/QueuePublisherXml.java
  src/com/magento/idea/magento2plugin/magento/files/QueueTopologyXml.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  testData/actions/generation/generator/QueueCommunicationGenerator/generateCommunicationXmlFile/communication.xml
  testData/actions/generation/generator/QueueConsumerGenerator/generateConsumerXmlFile/queue_consumer.xml
  testData/actions/generation/generator/QueuePublisherGenerator/generatePublisherXmlFile/queue_publisher.xml
  testData/actions/generation/generator/QueueTopologyGenerator/generateTopologyXmlFile/queue_topology.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueueCommunicationGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueueConsumerGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueuePublisherGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueueTopologyGeneratorTest.java
Labels: Award: category of expertise, Award: complex, Award: special achievement, Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#405 Added template description for Magento Regular Class
  resources/fileTemplates/internal/Magento Regular Class.php.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#425 #420 Fixed the Inject a ViewModel dialog
  CHANGELOG.md
  resources/magento2/common.properties
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#426 Updated test framework to Junit 4 and fixed ignored tests
  build.gradle
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCronGroupXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/ButtonMethodGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/ClassArgumentInXmlConfigGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplate.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplateUtil.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorHaveSetupVersionTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java
Labels: Award: advanced, Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#427 3.0.2 >3.1.0 forwardport
  CHANGELOG.md
  build.gradle
  resources/fileTemplates/internal/Magento Regular Class.php.html
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCronGroupXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/ButtonMethodGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/ClassArgumentInXmlConfigGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplate.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplateUtil.java
  testData/inspections/xml/ObserverDeclarationInspection/observerNameUsedInDifferentFile/events.xml
  testData/inspections/xml/ObserverDeclarationInspection/observerNameUsedInSameFile/events.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorHaveSetupVersionTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspectionTest.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#429 Fixed plugin name validator
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithColonRule.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: Award: bug fix, Partner: EY, Progress: approved, partners-contribution

#428 Fixed observer name validator
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
Labels: Award: bug fix, Partner: EY, Progress: approved, partners-contribution

#431 Backport of PR#429
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithColonRule.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: Partner: EY, Progress: approved, partners-contribution

#430 Backport of PR#428
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
Labels: Partner: EY, Progress: approved, partners-contribution

#435 Fixed NPTR exception in theme directory view model action
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: Award: bug fix, Partner: EY, Progress: approved, partners-contribution

#436 Fixed NPTR exception in theme directory view model action
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: Partner: EY, Progress: approved, partners-contribution

#432 Added inspection warning for disabled observer
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  testData/inspections/xml/ObserverDeclarationInspection/disablingNonExistingObserver/events.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspectionTest.java
Labels: Award: bug fix, Award: test coverage, Partner: EY, Progress: approved, partners-contribution

#412 Added explanation for Gradle, typo fix
  README.md
Labels: Cleanup, Progress: approved

#438 Fixed model generation with same names
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
Labels: Award: bug fix, Partner: EY, Progress: approved, partners-contribution

#442 [Code Generation] Fixing overriding a template from the base area
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
Labels: Partner: Atwix, Progress: ready for review, code generation, partners-contribution

#440 3.0.3 develop >3.1.0 develop forwardport
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution
