Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-04, with the labels that each got.

#72 Fixed .gitignore, change.log, contributing.md
  .github/CONTRIBUTING.md
  .gitignore
  CHANGELOG.md
  README.md
Labels: Partner: Atwix, Progress: review, partners-contribution

#73 Removed redundant file
  META-INF/plugin.xml
Labels: Partner: Atwix, partners-contribution

#74 Removing the not used packages that breaking the running IDE
  src/com/magento/idea/magento2plugin/reference/provider/mftf/PageReferenceProvider.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution, release-1.0.0

#78 Readme update
  README.md
Labels: Progress: approved

#79 Added test for CacheableFalseInDefaultLayoutInspection, updated inspe…
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
  testData/inspections/xml/CacheableFalseInDefaultLayoutInspection/withCacheableFalseBlock/default.xml
  testData/inspections/xml/CacheableFalseInDefaultLayoutInspection/withCacheableFalseBlockNotDefaultLayout/some_layout_index.xml
  testData/inspections/xml/CacheableFalseInDefaultLayoutInspection/withoutCacheableFalseBlock/default.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspectionTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#80 Automated tests added
  .github/workflows/gradle.yml
Labels: Award: advanced, Award: complex, Partner: Atwix, Progress: approved, partners-contribution, release-1.0.0

#77 Add license select to the new module
  resources/fileTemplates/internal/Magento Module Composer.json.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleComposerJsonData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
Labels: Award: special achievement, Partner: Atwix, Progress: review, partners-contribution

#76 #30: Completion. Remove PHP completions from all not appropriate places in XML files
  src/com/magento/idea/magento2plugin/completion/provider/ModuleNameCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/magento/files/CommonXml.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleAclXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleXml.java
Labels: Award: advanced, Award: bug fix, Award: special achievement, Progress: changes requested, Progress: needs update

#81 Show the current project's Magento version in settings window
  src/com/magento/idea/magento2plugin/actions/generation/util/MagentoVersion.java
  src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
  tests/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspectionTest.java
Labels: Award: advanced, Award: special achievement, Partner: Atwix, Progress: changes requested, partners-contribution

#92 📦 #58 Block Generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Common Php Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/BlockFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/NewBlockData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewBlockValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/magento/files/BlockPhp.java
  src/com/magento/idea/magento2plugin/magento/files/RegistrationPhp.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectory.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Partner: Atwix, Progress: review, action, code generation, partners-contribution, release-1.0.0

#95 [XmlCompletion] #91 - Added php class completion for source_model tag…
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleSystemXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleWidgetXml.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Partner: Smile, Progress: review, code generation, partners-contribution

#96 #90 :- Completion. Add PHP classes completion to the frontend_model attribute and tag
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleSystemXml.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Progress: changes requested, completion, release-1.0.0

#94 [TemplateDescription] #87 - Added description for dependency injectio…
  resources/fileTemplates/code/Magento Module DI Xml Preference.xml.ft
  resources/fileTemplates/code/Magento Module DI Xml Preference.xml.html
Labels: Event: Global-Contribution-Day, Partner: Smile, Progress: review, code generation, partners-contribution

#99 Line markers support for target plugin class and methods
  CHANGELOG.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/php/linemarker/PluginLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/php/linemarker/PluginTargetLineMarkerProvider.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Partner: Atwix, Progress: review, partners-contribution, release-1.0.0

#101 Allow to specify module dependencies when creating a new module
  resources/fileTemplates/internal/Magento Module Xml.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleComposerJsonData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Progress: approved, action, code generation, release-1.0.0

#102 Implemented #93: Action/Code Generation. Observer Generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Module Events Xml Observer.xml.ft
  resources/fileTemplates/code/Magento Module Events Xml Observer.xml.html
  resources/fileTemplates/code/Magento Observer Execute Method.php.ft
  resources/fileTemplates/code/Magento Observer Execute Method.php.html
  resources/fileTemplates/internal/Magento Module Events Xml.xml.ft
  resources/fileTemplates/internal/Magento Observer Class.php.ft
  resources/fileTemplates/internal/Magento Observer Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ObserverEventsXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ObserverFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEventsXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleEventsXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleFileInterface.java
  src/com/magento/idea/magento2plugin/magento/files/Observer.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
Labels: Event: Global-Contribution-Day

#108 #89 : Completion. Add PHP classes completion to the backend_model attribute and tag
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleConfigXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleSystemXml.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Progress: review, completion, release-1.0.0

#109 #84 :- Code generation. Module XML template description
  resources/fileTemplates/internal/Magento Module Xml.xml.html
Labels: Event: Global-Contribution-Day, Progress: approved, code generation, release-1.0.0

#113 [bugfix] Code generation: module block namespace is corrupt
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#97 #35: Inspection. GraphQL resolver should implement Resolver interface
  resources/META-INF/withJsGraphQl.xml
  resources/inspectionDescriptions/GraphQlResolverInspection.html
  src/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/fix/PhpImplementResolverClassQuickFix.java
  src/com/magento/idea/magento2plugin/magento/files/GraphQlResolver.java
  src/com/magento/idea/magento2plugin/php/linemarker/GraphQlResolverUsageLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUsagesCollector.java
  src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUtil.java
Labels: Award: special achievement, Event: Global-Contribution-Day, Progress: changes requested, inspection

#111 Code generation view model
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/NewViewModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ViewModelFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ViewModelPhp.java
Labels: Award: special achievement, Partner: Atwix, Progress: review, action, code generation, partners-contribution, release-1.0.0

#114 Added the short description for the plugin di.xml template
  resources/fileTemplates/code/Magento Module DI Xml Plugin.xml.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#116 Add the description for PHP preference class template
  resources/fileTemplates/internal/Magento Php Preference Class.php.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#120 Added the module's default license name at the project settings level
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/project/Settings.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
Labels: Award: special achievement, Partner: Atwix, action, enhancement, partners-contribution

#118 Add description for the module events.xml template
  resources/fileTemplates/internal/Magento Module Events Xml.xml.html
Labels: Partner: Atwix, Progress: approved, partners-contribution

#117 Added the observer's template must-have implemented method and template description
  resources/fileTemplates/internal/Magento Observer Class.php.ft
  resources/fileTemplates/internal/Magento Observer Class.php.html
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#122 92 tests on php class completion for the source model
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  testData/completion/common/classes.php
  testData/completion/common/system.xml
  testData/completion/common/widget.xml
  tests/com/magento/idea/magento2plugin/completion/xml/CompletionLightJavaCodeInsightFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/completion/xml/SourceModelXmlCompletionRegistrarTest.java
Labels: Award: complex, Award: test coverage, Partner: Smile, Progress: review, partners-contribution

#121 Add the possibility to enable/disable the MFTF support for the project
  src/com/magento/idea/magento2plugin/project/Settings.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/ActionGroupIndex.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/DataIndex.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/PageIndex.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/SectionIndex.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/StepKeyIndex.java
Labels: Award: special achievement, Partner: Atwix, Progress: review, partners-contribution, settings

#130 Added Magento 2 module project template
  CHANGELOG.md
  README.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleComposerJsonData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleRegistrationPhpData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/util/IsClickedDirectoryInsideProject.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/generation/MagentoModuleGenerator.java
  src/com/magento/idea/magento2plugin/generation/MagentoProjectGeneratorSettings.java
  src/com/magento/idea/magento2plugin/generation/MagentoProjectPeer.java
  src/com/magento/idea/magento2plugin/generation/MagentoTemplatesFactory.java
  src/com/magento/idea/magento2plugin/generation/NewModuleForm.form
  src/com/magento/idea/magento2plugin/generation/NewModuleForm.java
  src/com/magento/idea/magento2plugin/generation/validator/NewModuleFormValidator.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/init/ConfigurationManager.java
  src/com/magento/idea/magento2plugin/magento/files/ComposerJson.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  src/com/magento/idea/magento2plugin/project/ConfigurableProvider.java
  src/com/magento/idea/magento2plugin/project/ProjectDetector.java
  src/com/magento/idea/magento2plugin/project/Settings.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
  src/com/magento/idea/magento2plugin/project/UsagesProvider.java
  src/com/magento/idea/magento2plugin/project/util/GetProjectBasePath.java
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectory.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Labels: Award: advanced, Partner: Atwix, Progress: review, code generation, partners-contribution

#127 [bugfix] [Tests] Test coverage for PHP class completion for backend model; bugfix for #126
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleConfigXml.java
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/configXmlBackendModelAttributeDontMatchWithFile/other-file-than-config.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/configXmlBackendModelAttributeMatchWithFile/config.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/configXmlElementCompletionWontShow/config.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/configXmlElementProvideCompletion/config.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/systemXmlBackendModelAttributeDontMatchWithFile/other-file-than-system.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/systemXmlBackendModelAttributeMatchWithFile/system.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/systemXmlElementCompletionWontShow/system.xml
  testData/completion/common/xml/BackendModelXmlCompletionRegistrar/systemXmlElementProvideCompletion/system.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlAttributeMatchWithFileNegativeCase/not-widget.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlAttributeMatchWithFilePositiveCase/widget.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlAttributeMustProvideCompletion/widget.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlElementMatchWithFileNegativeCase/not-system.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlElementMatchWithFilePositiveCase/system.xml
  testData/completion/common/xml/SourceModelXmlCompletionRegistrar/sourceModelXmlElementMustProvideCompletion/system.xml
  tests/com/magento/idea/magento2plugin/completion/xml/BackendModelXmlCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/completion/xml/CompletionLightJavaCodeInsightFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/completion/xml/SourceModelXmlCompletionRegistrarTest.java
Labels: Award: bug fix, Award: special achievement, Award: test coverage, Partner: Atwix, partners-contribution

#125 #123: created GraphQl Resolver generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento GraphQL Resolver.php.ft
  resources/fileTemplates/code/Magento GraphQL Resolver.php.html
  resources/fileTemplates/internal/Magento GraphQL Resolver Class.php.ft
  resources/fileTemplates/internal/Magento GraphQL Resolver Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/GraphQlResolverFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/GraphQlResolverPhp.java
Labels: Award: special achievement, Partner: Atwix, Progress: changes requested, Progress: review, action, code generation, partners-contribution, release-1.0.0

#135 Extracting the validation messages into a separate bundle and making them more flexible
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewBlockValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/generation/validator/NewModuleFormValidator.java
  src/com/magento/idea/magento2plugin/validators/ValidatorBundle.java
Labels: Award: category of expertise, Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#137 Extracting existing messages into bundle
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java
Labels: Award: bug fix, Partner: Atwix, partners-contribution

#140 Fixed listeners on new module form for PHPStorm
  src/com/magento/idea/magento2plugin/generation/NewModuleForm.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#141 Refactoring the bundle messaging
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewBlockValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/bundles/AbstractBundle.java
  src/com/magento/idea/magento2plugin/bundles/ValidatorBundle.java
  src/com/magento/idea/magento2plugin/generation/validator/NewModuleFormValidator.java
  src/com/magento/idea/magento2plugin/validators/ValidatorBundle.java
Labels: Award: category of expertise, Partner: Atwix, Progress: approved, partners-contribution

#144 description for observer templates
  resources/fileTemplates/code/Magento Module Events Xml Observer.xml.html
  resources/fileTemplates/code/Magento Observer Execute Method.php.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#119 Added inspection for possible plugin duplication
  resources/META-INF/plugin.xml
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/bundles/InspectionBundle.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/indexes/PluginIndex.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java
  src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
Labels: Award: advanced, Partner: Atwix, QA passed, partners-contribution, release-1.0.0

#138 #115 : Tests. Cover the PHP GraphQL resolver inspection by tests
  testData/inspections/php/GraphQlResolverInspection/withInvalidResolverInterface/InvalidResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidResolverInterface/ValidResolverTest.php
  tests/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspectionTest.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
Labels: Award: special achievement, Award: test coverage, Progress: review, approved

#145 description for graphQL resolver templates
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento GraphQL Resolver Method Resolve.php.ft
  resources/fileTemplates/code/Magento GraphQL Resolver Method Resolve.php.html
  resources/fileTemplates/code/Magento GraphQL Resolver.php.html
  resources/fileTemplates/internal/Magento GraphQL Resolver Class.php.html
  src/com/magento/idea/magento2plugin/magento/files/GraphQlResolverPhp.java
Labels: Partner: Atwix, Progress: changes requested, Progress: review, QA failed, partners-contribution

#154 Covered with tests the PluginDuplicationInspection and refactored the implementation
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInAdminhtmlArea/etc/adminhtml/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInCrontabArea/etc/crontab/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInFrontendArea/etc/frontend/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInGlobalArea/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInGraphqlArea/etc/graphql/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInWebApiRestArea/etc/webapi_rest/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameAlreadyUsedInWebApiSoapArea/etc/webapi_soap/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameDuplicationWarningWontShow/di.xml
  testData/inspections/xml/PluginDeclarationInspection/pluginNameUsedInSameFile/di.xml
  testData/project/magento2/vendor/magento/module-backend/etc/adminhtml/di.xml
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/composer.json
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/etc/graphql/di.xml
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/registration.php
  testData/project/magento2/vendor/magento/module-catalog-rule-configurable/composer.json
  testData/project/magento2/vendor/magento/module-catalog-rule-configurable/etc/crontab/di.xml
  testData/project/magento2/vendor/magento/module-catalog-rule-configurable/registration.php
  testData/project/magento2/vendor/magento/module-catalog/etc/di.xml
  testData/project/magento2/vendor/magento/module-catalog/etc/frontend/di.xml
  testData/project/magento2/vendor/magento/module-catalog/etc/webapi_rest/di.xml
  testData/project/magento2/vendor/magento/module-catalog/etc/webapi_soap/di.xml
  testData/project/magento2/vendor/magento/module-theme/Block/Html/Topmenu.php
  testData/project/magento2/vendor/magento/module-theme/composer.json
  testData/project/magento2/vendor/magento/module-theme/registration.php
  tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: review, QA passed, approved, partners-contribution

#155 #45: add error message and fix error with not existing class
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#157 Wrong dependency declared in composer JSON when creating a module
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ComposerJson.java
Labels: Award: bug fix, Award: category of expertise, Partner: Atwix, Progress: review, QA passed, partners-contribution

#161 Fixed performance issues on Plugin Line Market
  src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java
Labels: Award: bug fix, Partner: Atwix, QA passed, partners-contribution

#162 Fixed null pointer exception
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
Labels: Award: bug fix, Partner: Atwix, QA passed, partners-contribution

#163 Fix issue with creating observer
  src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java
  src/com/magento/idea/magento2plugin/completion/provider/ModuleNameCompletionProvider.java
  src/com/magento/idea/magento2plugin/magento/files/Observer.java
Labels: Partner: Atwix, Progress: approved, Progress: review, QA passed, partners-contribution, release-1.0.0

#170 167: Add the Duplicated Plugin Usage in di XML inspection description
  resources/inspectionDescriptions/PluginDeclarationInspection.html
Labels: Award: bug fix, Community Insider: Magecom, Progress: review, QA passed, community-insider-contribution

#176 #143 Action/Code Generation. Cron job generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Crontab Cronjob Registration.xml.ft
  resources/fileTemplates/code/Magento Crontab Cronjob Registration.xml.html
  resources/fileTemplates/internal/Magento Cronjob Class.php.ft
  resources/fileTemplates/internal/Magento Cronjob Class.php.html
  resources/fileTemplates/internal/Magento Crontab Xml.xml.ft
  resources/fileTemplates/internal/Magento Crontab Xml.xml.html
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/CronjobClassData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/CrontabXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewCronjobValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCrontabXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/NamespaceBuilder.java
  src/com/magento/idea/magento2plugin/indexes/CronGroupIndex.java
  src/com/magento/idea/magento2plugin/magento/files/CronGroups.java
  src/com/magento/idea/magento2plugin/magento/files/CronjobTemplate.java
  src/com/magento/idea/magento2plugin/magento/files/CrontabXmlTemplate.java
  src/com/magento/idea/magento2plugin/stubs/indexes/CronGroupIndexer.java
  src/com/magento/idea/magento2plugin/util/CamelCaseToSnakeCase.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: Award: category of expertise, Award: complex, Partner: Atwix, Progress: review, QA passed, partners-contribution

#180 Improvement: module name must not be equal to the package name.
  resources/fileTemplates/internal/Magento Module Composer.json.ft
  resources/magento2/common.properties
  resources/magento2/inspection.properties
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
Labels: Award: category of expertise, Community Insider: Magecom, QA passed, community-insider-contribution

#181 Covered Cron Job Generator by an Integration test
  src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  testData/actions/generation/generator/CronjobClassGenerator/generateFile/CleanTableCronjob.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#173 Fixed null pointer exception on ObserverDeclarationInspection
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#172 Fixed Resolver inspection
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspection.java
  src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/magento/files/GraphQlResolver.java
  src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUtil.java
  testData/inspections/php/GraphQlResolverInspection/withInvalidResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidBatchResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidBatchServiceContractResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidResolverInterface/ResolverTest.php
  testData/project/magento2/vendor/magento/framework/BatchResolverInterface.php
  testData/project/magento2/vendor/magento/framework/BatchServiceContractResolverInterface.php
  testData/project/magento2/vendor/magento/framework/ResolverInterface.php
  testData/project/magento2/vendor/magento/module-catalog/etc/schema.graphqls
  tests/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspectionTest.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#165 Fixed error on around plugin
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#166 Fixed MFTF selector reference contributor and completion, added tes coverage
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustProvideCompletion/TestActionGroup.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustProvideCompletion/TestMftfTest.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustHaveReference/TestActionGroup.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustHaveReference/TestMftfTest.xml
  tests/com/magento/idea/magento2plugin/completion/xml/MftfSelectorCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/xml/MftfSelectorReferenceRegistrarTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#183 Fixed null pointer exception in the PluginDeclarationInspection
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#185 #156: fix issue with wrong namespaces
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/PluginMethodsGenerator.java
Labels: Award: bug fix, Award: special achievement, Partner: Atwix, Progress: review, partners-contribution, release-1.0.0

#175 #169 :- Quick fix for Resolver inspection adds implement directive to the next line
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/php/fix/PhpImplementResolverClassQuickFix.java
Labels: Award: bug fix, Award: category of expertise, Progress: review, inspection, release-1.0.0

#206 Update 1.0.1-develop with fixes from 1.0.0-develop
  resources/META-INF/plugin.xml
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/PluginMethodsGenerator.java
  src/com/magento/idea/magento2plugin/completion/provider/mftf/TestNameCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/fix/PhpImplementResolverClassQuickFix.java
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/magento/files/GraphQlResolver.java
  src/com/magento/idea/magento2plugin/magento/files/MftfTest.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/ActionGroupReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/DataReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/PageReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/SectionReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/TestNameReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/VariableToStepKeyProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/TestNameIndex.java
  src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUtil.java
  testData/completion/xml/MftfNameCompletionRegistrar/extendsInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/completion/xml/MftfNameCompletionRegistrar/extendsMustProvideCompletion/TestMftfTest.xml
  testData/completion/xml/MftfNameCompletionRegistrar/extendsSameNameMustBeEmpty/TestMftfTest.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustProvideCompletion/TestActionGroup.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml
  testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustProvideCompletion/TestMftfTest.xml
  testData/inspections/php/GraphQlResolverInspection/withInvalidResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidBatchResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidBatchServiceContractResolverInterface/ResolverTest.php
  testData/inspections/php/GraphQlResolverInspection/withValidResolverInterface/ResolverTest.php
  testData/project/magento2/vendor/magento/framework/BatchResolverInterface.php
  testData/project/magento2/vendor/magento/framework/BatchServiceContractResolverInterface.php
  testData/project/magento2/vendor/magento/framework/ResolverInterface.php
  testData/project/magento2/vendor/magento/module-catalog/etc/schema.graphqls
  testData/reference/xml/MftfNameReferenceRegistrar/extendsInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/reference/xml/MftfNameReferenceRegistrar/extendsMustHaveReference/TestMftfTest.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustHaveReference/TestActionGroup.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml
  testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustHaveReference/TestMftfTest.xml
  tests/com/magento/idea/magento2plugin/completion/xml/MftfNameCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/completion/xml/MftfSelectorCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspectionTest.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/MftfNameReferenceRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/xml/MftfSelectorReferenceRegistrarTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#205 Test coverage for type name attribute completion, linemarker and reference in the di.xml
  testData/completion/xml/ConfigurationTypeCompletionRegistrar/diXmlTypeNameMustHaveCompletion/di.xml
  testData/linemarker/php/ConfigurationTypeClassLinemarkerRegistrar/regularPhpClassShouldNotHaveLinemarker/ClassNotConfiguredInDiXml.php
  testData/linemarker/php/ConfigurationTypeClassLinemarkerRegistrar/typeNameClassShouldHaveLinemarker/Topmenu.php
  testData/reference/xml/ConfigurationTypeReferenceRegistrar/diXmlTypeNameMustHaveReference/di.xml
  tests/com/magento/idea/magento2plugin/completion/xml/ConfigurationTypeCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/ConfigurationTypeClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/xml/ConfigurationTypeReferenceRegistrarTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Atwix, partners-contribution

#207 Implemented custom file separator, utilize java.io.File breaks Windows
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/packages/File.java
  src/com/magento/idea/magento2plugin/util/magento/FileBasedIndexUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersion.java
  tests/com/magento/idea/magento2plugin/BaseProjectTestCase.java
  tests/com/magento/idea/magento2plugin/completion/xml/CompletionXmlFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/xml/InspectionXmlFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/LinemarkerPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/php/ReferencePhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/ReferenceXmlFixtureTestCase.java
Labels: Award: bug fix, Award: category of expertise, Partner: Atwix, Progress: review, partners-contribution

#209 Forward port custom file separator [207]
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/packages/File.java
  src/com/magento/idea/magento2plugin/util/magento/FileBasedIndexUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersion.java
  tests/com/magento/idea/magento2plugin/BaseProjectTestCase.java
  tests/com/magento/idea/magento2plugin/completion/xml/CompletionXmlFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/xml/InspectionXmlFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/LinemarkerPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/php/ReferencePhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/ReferenceXmlFixtureTestCase.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#208 Managing the static phrases to use the bundle messages
  resources/magento2/common.properties
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewBlockValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/bundles/CommonBundle.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#210 Added publish plugin configuration
  .github/workflows/gradlepublish.yml
  CHANGELOG.md
  build.gradle
Labels: Partner: Atwix, approved, partners-contribution

#211 Covered module.xml generator by test
  testData/actions/generation/generator/ModuleXmlGenerator/generateFileInRoot/module.xml
  testData/actions/generation/generator/ModuleXmlGenerator/generateModuleFile/module.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: review, approved, partners-contribution

#214 Cover composer.json generator by tests
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: review, partners-contribution

#215 Fix typos
  resources/fileTemplates/code/Magento Crontab Cronjob Registration.xml.html
  resources/fileTemplates/internal/Magento Php Preference Class.php.html
Labels: Award: cleanup, approved

#216 Forward port: Added publish plugin configuration
  .github/workflows/gradlepublish.yml
  CHANGELOG.md
  build.gradle
Labels: Partner: Atwix, Progress: review, partners-contribution

#220 Add di.xml template description
  resources/fileTemplates/internal/Magento Module DI Xml.xml.html
Labels: Partner: Something Digital, Progress: review, partners-contribution

#222 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Partner: Atwix, Progress: review, partners-contribution

#223 Added tests for WEB-API line markers, fixed performance issue
  src/com/magento/idea/magento2plugin/linemarker/php/WebApiLineMarkerProvider.java
  testData/linemarker/php/WebApiLinemarkerRegistrar/regularPhpClassShouldNotHaveLinemarker/ClassNotConfiguredInWebApiXml.php
  testData/linemarker/php/WebApiLinemarkerRegistrar/webApiServiceShouldHaveLinemarker/TestService.php
  testData/project/magento2/vendor/magento/module-catalog/etc/webapi.xml
  tests/com/magento/idea/magento2plugin/inspections/php/GraphQlResolverInspectionTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/WebApiLinemarkerRegistrarTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#225 194: Covered ModuleBlockClassGenerator by integration test
  testData/actions/generation/generator/ModuleBlockClassGenerator/generateFile/ViewBlock.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGeneratorTest.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#221 Increase the version for configuring deploy to alpha
  build.gradle
  resources/META-INF/plugin.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#219 Excluding current ActionGroup for completion when extending it
  src/com/magento/idea/magento2plugin/completion/provider/mftf/ActionGroupCompletionProvider.java
  src/com/magento/idea/magento2plugin/magento/files/MftfActionGroup.java
  testData/completion/xml/MftfNameCompletionRegistrar/extendsSameNameMustBeEmptyForActionGroup/TestActionGroup.xml
  tests/com/magento/idea/magento2plugin/completion/xml/MftfNameCompletionRegistrarTest.java
Labels: Award: bug fix, Partner: Atwix, approved, partners-contribution

#227 Fixing the positioning of all Dialogs on the center screen
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
Labels: Award: bug fix, Award: category of expertise, Partner: Atwix, approved, partners-contribution

#226 Replacing the dialog's labels by more standardized ones
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewCronjobValidator.java
  src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.form
Labels: Award: category of expertise, Partner: Atwix, Progress: review, approved, partners-contribution

#231 Deploy an alpha version only if PR has `deploy-alpha` label
  .github/workflows/gradlepublishalpha.yml
Labels: Award: cleanup, Partner: Atwix, Progress: review, partners-contribution

#230 #issue-198 Covered module View Model class generator with test
  testData/actions/generation/generator/ModuleViewModelClassGenerator/generateViewModelFile/TestViewModel.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#228 #issue-197 Covered module registration.php generator
  testData/actions/generation/generator/ModuleRegistrationPhpGenerator/generateRegistrationPhpFile/registration.php
  testData/actions/generation/generator/ModuleRegistrationPhpGenerator/generateRegistrationPhpFileInRoot/registration.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#232 #issue-196 Covered module grapahQl resolver generation
  testData/actions/generation/generator/ModuleGraphQlResolverClassGenerator/generateModuleGraphQlResolverClassFile/TestResolver.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#233 Fix for CreateAPluginAction accessible from the wrong context
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, deploy-alpha, partners-contribution

#235 #issue-199 Covered the observer class generator
  src/com/magento/idea/magento2plugin/actions/generation/data/ObserverFileData.java
  testData/actions/generation/generator/ObserverClassGenerator/generateObserverClass/TestObserver.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, Progress: review, partners-contribution

#234 #issue-200 Covered observer events.xml generator
  testData/actions/generation/generator/ObserverEventsXmlGenerator/addTwoObserversToOneEventsXml/events.xml
  testData/actions/generation/generator/ObserverEventsXmlGenerator/generateEventsXmlInAdminhtmlAreaFile/events.xml
  testData/actions/generation/generator/ObserverEventsXmlGenerator/generateEventsXmlInBaseAreaFile/events.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, approved, partners-contribution, test coverage request

#236 #issue-201 Covered Plugin Class generator
  testData/actions/generation/generator/PluginClassGenerator/generatePluginClassFile/TestPlugin.php
  testData/project/magento2/app/code/Foo/Bar/Service/SimpleService.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, Progress: review, partners-contribution

#237 #issue-202 Covered di.xml Generator
  testData/actions/generation/generator/PluginDiXmlGenerator/addTwoPluginsToOneDiXml/di.xml
  testData/actions/generation/generator/PluginDiXmlGenerator/addTwoPluginsToOneTargetClass/di.xml
  testData/actions/generation/generator/PluginDiXmlGenerator/generatePluginDiXmlFileForAdminhtmlArea/di.xml
  testData/actions/generation/generator/PluginDiXmlGenerator/generatePluginDiXmlFileForBaseArea/di.xml
  testData/project/magento2/app/code/Foo/Bar/Model/PluginTargetClassOne.php
  testData/project/magento2/app/code/Foo/Bar/Model/PluginTargetClassTwo.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGeneratorTest.java
Labels: Partner: Atwix, approved, partners-contribution

#239 Covered reference block related functionality with tests
  testData/completion/xml/LayoutBlockCompletionRegistrar/referenceBlockMustHaveCompletion/default.xml
  testData/project/magento2/vendor/magento/module-catalog/view/frontend/layout/test_index_index.xml
  testData/reference/xml/LayoutBlockReferenceRegistrar/referenceBlockMustHaveReference/default.xml
  tests/com/magento/idea/magento2plugin/completion/xml/LayoutBlockCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/LayoutBlockReferenceRegistrarTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#188 #184 Setup Code Style Checks 📦
  .github/workflows/gradle.yml
  build.gradle
  gradle-tasks/checkstyle/checkstyle.xml
  gradle-tasks/pmd/ruleset.xml
  gradle-tasks/staticChecks.gradle
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
Labels: Award: advanced, Award: category of expertise, Award: complex, Partner: Atwix, Priority: P1, Progress: review, Severity: S1, infrastructure, partners-contribution
