Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-10, with the labels that each got.

#282 89: UI Component form validation of the creation dialog
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewUiComponentFormValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/FieldValidation.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/FieldValidations.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AclResourceIdRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphanumericRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphanumericWithUnderscoreRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/DirectoryRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/Lowercase.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/NotEmptyRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/NumericRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpClassRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpNamespaceNameRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/RouteIdRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/StartWithNumberOrCapitalLetterRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/ValidationRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormButtonsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: Award: advanced, Award: category of expertise, Progress: review

#292 Generated ACL in scope of ui component form generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module ACL XML.xml.ft
  resources/fileTemplates/internal/Magento Module ACL XML.xml.html
  src/com/magento/idea/magento2plugin/actions/generation/data/AclXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateAclXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleAclXml.java
  src/com/magento/idea/magento2plugin/util/magento/GetAclResourcesListUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetAclResourcesTreeUtil.java
  src/com/magento/idea/magento2plugin/util/xml/XmlPsiTreeUtil.java
  testData/actions/generation/generator/AclXmlGenerator/generateAclXmlFile/acl.xml
  testData/actions/generation/generator/AclXmlGenerator/generateAclXmlFileForNonExistedParent/acl.xml
  testData/actions/generation/generator/AclXmlGenerator/getAclXmlFileAndGenerateNewAcl/acl.xml
  testData/project/magento2/vendor/magento/module-backend/etc/acl.xml
  testData/project/magento2/vendor/magento/module-config/composer.json
  testData/project/magento2/vendor/magento/module-config/etc/acl.xml
  testData/project/magento2/vendor/magento/module-config/etc/module.xml
  testData/project/magento2/vendor/magento/module-config/registration.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGeneratorTest.java
Labels: Award: advanced, Award: test coverage, Progress: review

#307 Added new validation for new ViewModel dialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java
Labels: Progress: review

#308 306: Added highlighting in error style to JComponent elements
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/HighlightDialogFieldOnErrorUtil.java
Labels: Award: category of expertise, Progress: review

#280 [212]_add reference navigation and completion for crontab.xml
  src/com/magento/idea/magento2plugin/completion/provider/PhpJobMethodCompletionContributor.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/DiIndex.java
  src/com/magento/idea/magento2plugin/magento/files/CommonXml.java
  src/com/magento/idea/magento2plugin/reference/provider/PhpJobMethodReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
Labels: Award: advanced, Progress: review

#310 Added test coverage for references and completions of crontab instance and method
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/reference/provider/PhpJobMethodReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  testData/completion/xml/CrontabCompletionRegistrar/cronJobInstanceMustHaveCompletion/crontab.xml
  testData/completion/xml/CrontabCompletionRegistrar/cronJobMethodMustHaveCompletion/crontab.xml
  testData/completion/xml/CrontabCompletionRegistrar/notCrontabXmlMethodMustHaveNotCompletion/wrong_named_crontab.xml
  testData/completion/xml/CrontabCompletionRegistrar/notCrontabXmlMustHaveNotCompletion/wrong_named_crontab.xml
  testData/completion/xml/CrontabCompletionRegistrar/notInstanceAttrMustHaveNotCompletion/crontab.xml
  testData/completion/xml/CrontabCompletionRegistrar/notJobTagMustHaveNotCompletion/crontab.xml
  testData/project/magento2/vendor/magento/module-catalog/Cron/RefreshSpecialPrices.php
  testData/reference/xml/CrontabReferenceRegistrar/crontabInstanceMustHaveReference/crontab.xml
  testData/reference/xml/CrontabReferenceRegistrar/crontabMethodMustHaveReference/crontab.xml
  tests/com/magento/idea/magento2plugin/completion/xml/CrontabCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/xml/CrontabReferenceRegistrarTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: review, hacktoberfest-accepted

#284 Added menu.xml parent menu completion and reference
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/completion/provider/MenuCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleMenuXml.java
  src/com/magento/idea/magento2plugin/reference/provider/MenuReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/MenuIndex.java
  testData/completion/xml/MenuCompletionRegistrar/addTagMustHaveCompletion/menu.xml
  testData/project/magento2/vendor/magento/module-catalog/etc/adminhtml/menu.xml
  testData/reference/xml/MenuReferenceRegistrar/addTagMustHaveCompletion/menu.xml
  tests/com/magento/idea/magento2plugin/completion/xml/MenuCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/xml/MenuReferenceRegistrarTest.java
Labels: Award: advanced, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#311 Added menu.xml, acl.xml, controller and layout to UI component grid generation
  resources/fileTemplates/code/Magento Module Class Arguments In Xml.xml.html
  resources/fileTemplates/internal/Magento Menu Xml.xml.ft
  resources/fileTemplates/internal/Magento Menu Xml.xml.html
  resources/fileTemplates/internal/Magento Module Controller Backend Class.php.ft
  resources/fileTemplates/internal/Magento Module Ui Custom Data Provider Php.php.ft
  resources/fileTemplates/internal/Magento Module Ui Grid Collection Data Provider Php.php.ft
  resources/fileTemplates/internal/Magento Module Ui Grid Collection Data Provider Php.php.html
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentFormAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DataProviderDeclarationData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/LayoutXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MenuXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentDataProviderData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewUiComponentGridDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataProviderDeclarationGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/LayoutXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MenuXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/CommitXmlFileUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateMenuXml.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/PluginIndex.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleMenuXml.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentDataProviderPhp.java
  testData/actions/generation/generator/DataProviderDeclarationGenerator/generateDataProviderDeclarationFile/di.xml
  testData/actions/generation/generator/MenuXmlGenerator/generateMenuXmlFile/menu.xml
  testData/actions/generation/generator/ModuleControllerClassGenerator/generateBackendControllerFile/BackendSaveAction.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCollectionDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DataProviderDeclarationGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/MenuXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
Labels: Award: advanced, Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#315 Refactored settings form
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#316 2.0.1-develop initial
  .github/workflows/gradle.yml
  build.gradle
  resources/META-INF/plugin.xml
Labels: Award: cleanup, Partner: Atwix, Progress: approved, partners-contribution

#314 Updated changelog
  CHANGELOG.md
  build.gradle
Labels: Partner: Atwix, Progress: approved, hacktoberfest-accepted, partners-contribution

#313 Adjusted UI form XML to be valid and accessible via the admin
  resources/fileTemplates/internal/Magento Module UI Component Form Xml.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentFormFieldsetData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGeneratorTest.java
Labels: Award: test coverage, Partner: Atwix, Progress: approved, QA passed, approved, hacktoberfest-accepted, partners-contribution

#320 Added form field status to reflect plugin status
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
Labels: Award: bug fix, Partner: Zilker Technology, Progress: review, QA passed, partners-contribution

#317 Fixed validator when plugin is disabled
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java
Labels: Partner: Zilker Technology, partners-contribution

#323 Fixing the dialog size. Fixing adding new form fieldset
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#329 Fixing name column
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
Labels: Partner: Atwix, partners-contribution

#319 Changed new controller dialog validator
  resources/magento2/common.properties
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewControllerValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpDirectoryRule.java
Labels: Award: category of expertise, Partner: Zilker Technology, Progress: review, QA failed, hacktoberfest-accepted, partners-contribution

#318 Changed new module dialog validator
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java
Labels: Partner: Zilker Technology, Progress: changes requested, partners-contribution

#334 Forwardport 2.0.0 >2.0.1
  CHANGELOG.md
  build.gradle
  resources/fileTemplates/internal/Magento Module UI Component Form Xml.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentFormFieldsetData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGeneratorTest.java
Labels: Award: cleanup, Partner: Atwix, partners-contribution

#335 Fixed new module action
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#327 Changed validator for NewGraphQlResolverDialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java
Labels: Partner: Zilker Technology, Progress: on hold, partners-contribution

#337 Changed validator for OverrideClassByAPreferenceDialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#333 Changed validator for InjectAViewModelDialog
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/InjectAViewModelDialogValidator.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#338 Changed validator for NewCLICommandDialog
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewCLICommandValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/CliCommandRule.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#336 Changed validator for CreateAnObserverDialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpClassRule.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#343 Add gradle cache to speed up builds
  .github/workflows/gradle.yml
Labels: Award: category of expertise, Event: MageCONF CD 2020, Progress: review

#324 Changed validator for CreateAPluginDialog
  resources/magento2/common.properties
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
Labels: Award: category of expertise, Mageconf_Contribution_Day, Partner: Zilker Technology, Progress: review, partners-contribution

#345 Improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Event: MageCONF CD 2020

#346 Changed validator for NewCronGroupDialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewCronGroupValidator.java
Labels: Event: MageCONF CD 2020, Partner: Zilker Technology, Progress: review, partners-contribution

#344 Fixed disabling plugin on a startup when Magento not in the root
  src/com/magento/idea/magento2plugin/project/startup/CheckIfMagentoPathIsValidActivity.java
Labels: Event: MageCONF CD 2020, Partner: Atwix, Progress: review, partners-contribution

#348 Fixed directory structure for the override in theme action
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
Labels: Award: bug fix, Event: MageCONF CD 2020, Partner: Atwix, Progress: review, partners-contribution

#340 Forwardport 2.0.1 >2.1.0
  .github/workflows/gradle.yml
  CHANGELOG.md
  build.gradle
  resources/fileTemplates/internal/Magento Module UI Component Form Xml.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentFormFieldsetData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  src/com/magento/idea/magento2plugin/project/startup/CheckIfMagentoPathIsValidActivity.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
  testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGeneratorTest.java
Labels: Award: cleanup, Partner: Atwix, Progress: review, partners-contribution

#349 #291 :- Add routes.xml code template description
  resources/fileTemplates/internal/Magento Php Preference Class.php.html
  resources/fileTemplates/internal/Magento Routes Xml.xml.html
Labels: Award: bug fix, Event: MageCONF CD 2020, Progress: review

#326 Changed validator for OverrideInThemeDialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInTheme.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideInThemeDialogValidator.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#353 Add pure function liveTemplate
  resources/META-INF/plugin.xml
  resources/liveTemplates/MagentoPWA.xml
Labels: Award: bug fix, Partner: TechDivision, Progress: review, partners-contribution

#354 #305_Add reference navigation and autocomplete for UI component
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/completion/provider/UiComponentCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/UIComponentIndex.java
  src/com/magento/idea/magento2plugin/reference/provider/UIComponentReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/UIComponentIndex.java
Labels: Award: complex, Progress: review

#355 # 15 Fixed library root
  resources/META-INF/plugin.xml
  resources/phpstorm.meta.php/di-autocomplete.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#357 #305_update unit test
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  testData/completion/xml/LayoutUIComponentCompletionRegistrar/uIComponentMustHaveCompletion/default.xml
  testData/project/magento2/vendor/magento/module-catalog/view/frontend/ui_component/recently_viewed.xml
  testData/project/magento2/vendor/magento/module-catalog/view/frontend/ui_component/recently_viewed_2.xml
  testData/reference/xml/LayoutUIComponentReferenceRegistrar/uIComponentMustHaveReference/default.xml
  tests/com/magento/idea/magento2plugin/completion/xml/LayoutUIComponentCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/LayoutUIComponentReferenceRegistrarTest.java
Labels: Award: category of expertise, Award: test coverage, Progress: review

#358 Added BoxNotEmptyRule to validators
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
Labels: Award: bug fix, Award: special achievement, Partner: Zilker Technology, Progress: review, partners-contribution

#328 Fixed interface plugin linemarker
  src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#359 Added linemarker for interface plugin target (backport)
  src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java
Labels: Partner: Zilker Technology, Progress: on hold, on hold, partners-contribution

#351 Added index, completion and references for table names, column names …
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/completion/provider/ColumnNameCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/provider/TableNameCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaXml.java
  src/com/magento/idea/magento2plugin/reference/provider/TableColumnNamesReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/DeclarativeSchemaElementsIndex.java
  testData/completion/xml/TableAndColumnNameCompletionRegistrar/constraintColumnNameMustHaveCompletion/db_schema.xml
  testData/completion/xml/TableAndColumnNameCompletionRegistrar/constraintReferenceColumnNameMustHaveCompletion/db_schema.xml
  testData/completion/xml/TableAndColumnNameCompletionRegistrar/constraintTagReferenceTableMustHaveCompletion/db_schema.xml
  testData/completion/xml/TableAndColumnNameCompletionRegistrar/constraintTagTableMustHaveCompletion/db_schema.xml
  testData/completion/xml/TableAndColumnNameCompletionRegistrar/tableNameMustHaveCompletion/db_schema.xml
  testData/project/magento2/vendor/magento/module-catalog/etc/db_schema.xml
  testData/reference/xml/TableNameAndColumnReferenceRegistrar/constraintColumnTagMustHaveReference/db_schema.xml
  testData/reference/xml/TableNameAndColumnReferenceRegistrar/constraintReferenceColumnTagMustHaveReference/db_schema.xml
  testData/reference/xml/TableNameAndColumnReferenceRegistrar/constraintReferenceTableTagMustHaveReference/db_schema.xml
  testData/reference/xml/TableNameAndColumnReferenceRegistrar/constraintTableTagMustHaveReference/db_schema.xml
  testData/reference/xml/TableNameAndColumnReferenceRegistrar/tableTagMustHaveReference/db_schema.xml
  tests/com/magento/idea/magento2plugin/completion/xml/TableAndColumnNameCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/TableNameAndColumnReferenceRegistrarTest.java
Labels: Award: complex, Award: test coverage, Event: MageCONF CD 2020, Partner: Atwix, Progress: review, partners-contribution

#360 Added tests for PluginTargetLineMarkerProvider
  testData/linemarker/php/PluginTargetLinemarkerRegistrar/pluginToClassShouldHaveLinemarker/Topmenu.php
  testData/linemarker/php/PluginTargetLinemarkerRegistrar/pluginToInterfaceShouldHaveLinemarker/MviewState.php
  testData/linemarker/php/PluginTargetLinemarkerRegistrar/regularClassShouldNotHaveLinemarker/ClassNotConfiguredInDiXml.php
  testData/project/magento2/vendor/magento/framework/Mview/View/StateInterface.php
  testData/project/magento2/vendor/magento/module-catalog/etc/di.xml
  tests/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLinemarkerRegistrarTest.java
Labels: Award: test coverage, Partner: Zilker Technology, Progress: review, partners-contribution

#361 Added tests for GraphQL linemarkers
  testData/linemarker/graphqls/GraphQlResolverClassLinemarkerRegistrar/withValidSchemaResolver/schema.graphqls
  testData/linemarker/php/GraphQlResolverUsageLinemarkerRegistrar/regularClassShouldNotHaveLinemarker/ClassNotConfiguredInSchema.php
  testData/linemarker/php/GraphQlResolverUsageLinemarkerRegistrar/resolverClassShouldHaveLinemarker/Resolver.php
  tests/com/magento/idea/magento2plugin/linemarker/LinemarkerFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/linemarker/graphqls/GraphQlResolverClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/ConfigurationTypeClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/LinemarkerPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/linemarker/php/ObserverClassLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLinemarkerRegistrarTest.java
  tests/com/magento/idea/magento2plugin/linemarker/php/WebApiLinemarkerRegistrarTest.java
Labels: Award: category of expertise, Award: test coverage, Partner: Zilker Technology, Progress: review, partners-contribution

#362 Added test for PluginLineMarkerProvider
  testData/linemarker/php/PluginLinemarkerRegistrar/classWithPluginShouldHaveLinemarker/PluginClass.php
  testData/linemarker/php/PluginLinemarkerRegistrar/classWithoutPluginShouldNotHaveLinemarker/RegularClass.php
  testData/project/magento2/vendor/magento/module-catalog/Plugin/PluginClass.php
  testData/project/magento2/vendor/magento/module-catalog/etc/di.xml
  tests/com/magento/idea/magento2plugin/linemarker/php/PluginLinemarkerRegistrarTest.java
Labels: Award: test coverage, Partner: Zilker Technology, Progress: review, partners-contribution

#363 Refactored all generation dialog titles
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentFormAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentGridAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
Labels: Award: bug fix, Award: special achievement, Partner: Zilker Technology, Progress: review, partners-contribution

#365 Module layout file template description
  resources/fileTemplates/internal/Magento Module Layout Xml.xml.html
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#364 Fixed incorrect completion for general MFTF text tag attributes
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
Labels: Award: bug fix, Partner: Zilker Technology, Progress: review, partners-contribution

#367 Module name completion and reference tests
  testData/completion/xml/ModuleNameCompletionRegistrar/moduleNameMustHaveCompletion/module.xml
  testData/completion/xml/ModuleNameCompletionRegistrar/sequenceModuleNameMustHaveCompletion/module.xml
  testData/reference/xml/ModuleNameReferenceRegistrar/moduleNameMustHaveReference/module.xml
  testData/reference/xml/ModuleNameReferenceRegistrar/sequenceModuleNameMustHaveReference/module.xml
  tests/com/magento/idea/magento2plugin/completion/xml/ModuleNameCompletionRegistrarTest.java
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/xml/ModuleNameReferenceRegistrarTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Zilker Technology, Progress: review, partners-contribution
