Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-03, with the labels that each got.

#26 Added Plugin inspection and plugin method generation action
  META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/ImportReferences/PhpClassReferenceExtractor.java
  src/com/magento/idea/magento2plugin/actions/generation/ImportReferences/PhpClassReferenceResolver.java
  src/com/magento/idea/magento2plugin/actions/generation/ImportReferences/PhpClassReferenceStorage.java
  src/com/magento/idea/magento2plugin/actions/generation/MagentoGenerateAfterMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/MagentoGenerateAroundMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/MagentoGenerateBeforeMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/MagentoGeneratePluginMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MagentoPluginMethodData.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MagentoPluginMethodsGenerator.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/util/PhpClassImplementsInterfaceUtil.java
  src/com/magento/idea/magento2plugin/util/GetPhpClassByFQN.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/GetTargetClassNamesByPluginClassName.java
Labels: release-1.0.0

#32 Line Markers for GraphQl navigation
  META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/graphql/linemarker/GraphQlResolverClassLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/php/linemarker/GraphQlResolverUsageLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
  src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUtil.java
Labels: release-1.0.0

#25 Added the Require JS mapping reference navigation support
  META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/completion/provider/RequireJsMappingCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/indexes/JsIndex.java
  src/com/magento/idea/magento2plugin/indexes/LibJsIndex.java
  src/com/magento/idea/magento2plugin/reference/js/JsReferenceContributor.java
  src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/RequireJsPreferenceReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/provider/util/GetAllSubFilesOfVirtualFileUtil.java
  src/com/magento/idea/magento2plugin/reference/provider/util/GetFilePathUtil.java
  src/com/magento/idea/magento2plugin/reference/provider/util/GetModuleFileUtil.java
  src/com/magento/idea/magento2plugin/reference/provider/util/GetModuleNameUtil.java
  src/com/magento/idea/magento2plugin/reference/provider/util/GetModuleSourceFilesUtil.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/js/MagentoLibJsIndex.java
  src/com/magento/idea/magento2plugin/stubs/indexes/js/RequireJsIndex.java
Labels: release-1.0.0

#21 [WIP] Adds PhpStorm's meta plugin file
  .phpstorm.meta.php/di-autocomplete.php
  META-INF/plugin.xml
Labels: release-1.0.0

#47 add build dir to ignore
  .gitignore
Labels: Award: complex

#50 #44 :- Templates. Fill information about Plugin Templates
  resources/fileTemplates/code/Magento Plugin After Method.html
  resources/fileTemplates/code/Magento Plugin After Method.php.html
  resources/fileTemplates/code/Magento Plugin Around Method.html
  resources/fileTemplates/code/Magento Plugin Around Method.php.html
  resources/fileTemplates/code/Magento Plugin Before Method.html
  resources/fileTemplates/code/Magento Plugin Before Method.php.html
Labels: approved, code generation, release-1.0.0

#52 MVP implementation of the New Magento 2 Module action
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Composer.json.ft
  resources/fileTemplates/internal/Magento Module Registration Php.php.ft
  resources/fileTemplates/internal/Magento Module Xml.xml.ft
  resources/icons/module.png
  resources/icons/webapi.png
  src/com/magento/idea/magento2plugin/MagentoIcons.java
  src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewMagentoModuleDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DirectoryGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/data/ModuleDirectoriesData.java
  src/com/magento/idea/magento2plugin/magento/files/ComposerJson.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleFileInterface.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleXml.java
  src/com/magento/idea/magento2plugin/magento/files/RegistrationPhp.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoPackages.java
  src/com/magento/idea/magento2plugin/util/CamelCaseToHyphen.java
  src/com/magento/idea/magento2plugin/util/Regex.java
Labels: Award: complex, Partner: Atwix, action, code generation, partners-contribution, release-1.0.0

#60 JSGraphql configured as an optional dependency
  resources/META-INF/plugin.xml
  resources/META-INF/withJsGraphQl.xml
  src/com/magento/idea/magento2plugin/php/linemarker/GraphQlResolverUsageLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
Labels: Award: advanced, Partner: Atwix, approved, partners-contribution, release-1.0.0

#59 #27 [Inspection] Observer declaration check for duplicates
  CHANGELOG.md
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ObserverDeclarationInspection.html
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoPackages.java
Labels: Award: special achievement, Partner: Atwix, approved, inspection, partners-contribution, release-1.0.0

#63 Action/Code Generation. Plugin class generation from a class method
  CHANGELOG.md
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Module DI Xml Plugin.xml.ft
  resources/fileTemplates/code/Magento Module DI Xml Plugin.xml.html
  resources/fileTemplates/code/Magento Plugin After Method.php.html
  resources/fileTemplates/code/Magento Plugin Around Method.php.html
  resources/fileTemplates/code/Magento Plugin Before Method.php.html
  resources/fileTemplates/internal/Magento Module DI Xml.xml.ft
  resources/inspectionDescriptions/PluginInspection.html
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateAfterMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateAroundMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateBeforeMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGeneratePluginMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MagentoPluginDiXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MagentoPluginFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MagentoPluginMethodData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MagentoPluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MagentoPluginDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MagentoPluginMethodsGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/DirectoryGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplate.java
  src/com/magento/idea/magento2plugin/actions/generation/util/CodeStyleSettings.java
  src/com/magento/idea/magento2plugin/actions/generation/util/CollectInsertedMethods.java
  src/com/magento/idea/magento2plugin/actions/generation/util/FillTextBufferWithPluginMethods.java
  src/com/magento/idea/magento2plugin/actions/generation/util/NavigateToCreatedFile.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoPackages.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoPhpClass.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  src/com/magento/idea/magento2plugin/ui/FilteredComboBox.java
  src/com/magento/idea/magento2plugin/util/GetFirstClassOfFile.java
  src/com/magento/idea/magento2plugin/util/Regex.java
  src/com/magento/idea/magento2plugin/util/magento/FileBasedIndexUtil.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethod.java
Labels: Award: advanced, Award: complex, Partner: Atwix, action, code generation, partners-contribution, release-1.0.0

#62 #29 :- Inspection for using a block cacheable="false" attribute within default layout
  CHANGELOG.md
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/CacheableFalseInDefaultLayoutInspection.html
  src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/fix/XmlRemoveCacheableAttributeQuickFix.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
Labels: Award: special achievement, approved, inspection, release-1.0.0

#65 Refactoring code generation
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateAfterMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateAroundMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateBeforeMethodAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleComposerJsonData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleRegistrationPhpData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/PluginDiXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/PluginFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/code/PluginMethodData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/FileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/PluginMethodsGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/DirectoryGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/util/FillTextBufferWithPluginMethods.java
Labels: Partner: Atwix, partners-contribution

#66 Module's composer.json template adjustments
  resources/fileTemplates/internal/Magento Module Composer.json.ft
  resources/fileTemplates/internal/Magento Module Composer.json.html
Labels: Partner: Atwix, approved, code generation, partners-contribution, release-1.0.0
