Repository magento/magento2-phpstorm-plugin, pull requests merged in 2020-09, with the labels that each got.

#277 270: fixed endless loop of notifications
  build.gradle
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.java
  src/com/magento/idea/magento2plugin/project/Settings.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
  src/com/magento/idea/magento2plugin/project/startup/CheckIfMagentoPathIsValidActivity.java
  src/com/magento/idea/magento2plugin/stubs/indexes/js/MagentoLibJsIndex.java
  src/com/magento/idea/magento2plugin/util/magento/IsFileInEditableModuleUtil.java
Labels: Award: bug fix, Award: category of expertise, Partner: Atwix, Progress: approved, partners-contribution

#268 262: Change the CLI command namespace
  build.gradle
  resources/magento2/common.properties
  testData/actions/generation/generator/CLICommandClassGenerator/generateCLICommandClass/TestCLICommandPHPClass.php
  testData/actions/generation/generator/CLICommandDiXmlGenerator/addingTwoCLICommandToDiXml/di.xml
  testData/actions/generation/generator/CLICommandDiXmlGenerator/initializeCLICommand/di.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandClassGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandDiXmlGeneratorTest.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#264 #issue-83 Added UI component Grid generation with data provider generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module UI Component Grid Xml.xml.ft
  resources/fileTemplates/internal/Magento Module UI Component Grid Xml.xml.html
  resources/fileTemplates/internal/Magento Module Ui Grid Collection Data Provider Php.php.ft
  resources/fileTemplates/internal/Magento Module Ui Grid Collection Data Provider Php.php.html
  resources/fileTemplates/internal/Magento Module Ui Grid Custom Data Provider Php.php.ft
  resources/fileTemplates/internal/Magento Module Ui Grid Custom Data Provider Php.php.html
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentGridAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridDataProviderData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridToolbarData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewUiComponentGridDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentGridDataProviderPhp.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentGridXml.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  src/com/magento/idea/magento2plugin/util/magento/GetResourceCollections.java
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCollectionDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridXmlGenerator/generateUiGridForBaseArea/custom_entity_grid.xml
  testData/actions/generation/generator/UiComponentGridXmlGenerator/generateUiGridWithoutToolbar/custom_entity_grid.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGeneratorTest.java
Labels: Award: advanced, Award: complex, Award: test coverage, Partner: Atwix, Progress: review, partners-contribution

#224 Add Override in Theme Action
  build.gradle
  resources/META-INF/plugin.xml
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/OverrideInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInTheme.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideInThemeDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/magento/packages/ComponentType.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetComponentNameByDirectoryUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetComponentTypeByNameUtil.java
Labels: Award: category of expertise, Award: complex, Partner: Something Digital, Progress: review, action, code generation, partners-contribution

#279 Improving the plugin's arguments inspection
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution
