Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-02, with the labels that each got.

#467 Extended .phpstorm.meta.php for more convenient autocomplete
  resources/phpstorm.meta.php/di-autocomplete.php
Labels: Progress: approved

#468 [Backport 3.1.0] Extend .phpstorm.meta.php for more convenient autocomplete
  CHANGELOG.md
  resources/phpstorm.meta.php/di-autocomplete.php
Labels: Progress: review

#471 Fixing the PhpStorm META path
  resources/.phpstorm.meta.php/di-autocomplete.php
  resources/META-INF/plugin.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#465 added generator for save controller
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Entity Save Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Save Controller Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityControllerFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/DirectoryGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/actions/SaveActionFile.java
  src/com/magento/idea/magento2plugin/magento/packages/HttpMethod.java
  src/com/magento/idea/magento2plugin/magento/packages/code/BackendModuleType.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityActionGeneratorTest.java
Labels: Award: complex, Partner: Atwix, Progress: approved, partners-contribution

#470 Added entity data mapper generator and test for generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Entity Data Mapper.html.ft
  resources/fileTemplates/code/Magento Entity Data Mapper.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/EntityDataMapperData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/EntityDataMapperFile.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/actions/generation/generator/EntityDataMapperClassGenerator/generateEntityDataMapperFile/UnicornDataMapper.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperClassGeneratorTest.java
Labels: Award: complex, Award: test coverage, Progress: approved

#463 Added save entity command class generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Save Entity Command Model.php.ft
  resources/fileTemplates/internal/Magento Save Entity Command Model.php.html
  src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityCommandData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/commands/SaveEntityCommandFile.java
  src/com/magento/idea/magento2plugin/magento/packages/code/ExceptionType.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/actions/generation/generator/SaveEntityCommandGenerator/generateSaveEntityCommandFile/SaveCommand.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#473 Fixed few bugs with entity manager generation
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#476 Added entity columns to grid, recreated view controller, bug fixing, added actions column generation, test coverage
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Grid UI Component Column.xml.ft
  resources/fileTemplates/code/Magento Grid UI Component Column.xml.html
  resources/fileTemplates/internal/Magento Entity Index Adminhtml Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Index Adminhtml Controller Class.php.html
  resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.ft
  resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.html
  resources/fileTemplates/internal/Magento UI Component Grid XML.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/AdminListViewEntityActionData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/GridActionColumnData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/AdminListViewEntityActionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/GridActionColumnFile.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentGridXml.java
  src/com/magento/idea/magento2plugin/magento/files/actions/AdminListViewActionFile.java
  src/com/magento/idea/magento2plugin/magento/files/actions/SaveActionFile.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/actions/generation/generator/AdminListViewEntityControllerGenerator/generateListViewControllerFile/Index.php
  testData/actions/generation/generator/GridActionColumnFileGenerator/generateGridActionColumnFile/BlockActions.php
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/AdminListViewEntityControllerGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityActionGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#477 Added linemarkers for test fixtures
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/indexes/FixtureIndex.java
  src/com/magento/idea/magento2plugin/linemarker/php/TestFixtureLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/magento/files/TestFixture.java
  testData/linemarker/php/FixtureLinemarkerRegistrar/magentoApiDataFixtureHaveLinemarker/Test.php
  testData/linemarker/php/FixtureLinemarkerRegistrar/magentoDataFixtureHaveLinemarker/Test.php
  testData/project/magento2/dev/tests/integration/testsuite/Magento/Catalog/_files/test_fixture.php
  tests/com/magento/idea/magento2plugin/linemarker/php/TestFixtureLinemarkerRegistrarTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#466 Pre release 3.1.0
  CHANGELOG.md
  README.md
  resources/.phpstorm.meta.php/di-autocomplete.php
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Data Model Interface.php.ft
  resources/fileTemplates/internal/Magento Data Model.php.ft
  resources/fileTemplates/internal/Magento Message Queue Consumer Class.php.ft
  resources/fileTemplates/internal/Magento Message Queue Consumer Class.php.html
  resources/fileTemplates/internal/Magento Message Queue Handler Class.php.ft
  resources/fileTemplates/internal/Magento Message Queue Handler Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/MessageQueueClassData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/QueueConsumerData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueueConsumerGenerator.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
  src/com/magento/idea/magento2plugin/magento/files/MessageQueueClassPhp.java
  src/com/magento/idea/magento2plugin/magento/packages/MessageQueueConnections.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
  testData/actions/generation/generator/DataModelGenerator/generateDataModel/Sample.php
  testData/actions/generation/generator/DataModelGenerator/generateDataModelWithoutInterface/Sample.php
  testData/actions/generation/generator/DataModelInterfaceGenerator/generateDataModelInterface/SampleInterface.php
  testData/actions/generation/generator/MessageQueueClassGenerator/generateConsumer/MyConsumer.php
  testData/actions/generation/generator/MessageQueueClassGenerator/generateHandler/MyHandler.php
  testData/actions/generation/generator/QueueConsumerGenerator/generateConsumerAmpqXmlFile/queue_consumer.xml
  testData/actions/generation/generator/QueueConsumerGenerator/generateConsumerDbXmlFile/queue_consumer.xml
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/Model/Resolver/ImplementsBatchResolverInterface.php
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/Model/Resolver/ImplementsBatchServiceContractResolverInterface.php
  testData/project/magento2/vendor/magento/module-catalog-graph-ql/Model/Resolver/ImplementsResolverInterface.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueueConsumerGeneratorTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#478 Develop UI component form generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento PHP Form Generic Button Block Class.php.ft
  resources/fileTemplates/internal/Magento PHP Form Generic Button Block Class.php.html
  resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/FormGenericButtonBlockData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/FormGenericButtonBlockFile.java
  src/com/magento/idea/magento2plugin/magento/packages/uiComponent/FormElementType.java
  testData/actions/generation/generator/FormGenericButtonBlockGenerator/generateFormGenericButtonBlockFile/GenericButton.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGeneratorTest.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#483 Improved UX by adding autocompletion for entity name dependent fields
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
Labels: Partner: Atwix, Progress: approved, QA passed, partners-contribution

#484 Added ui components tab toggling
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Partner: Atwix, Progress: approved, QA passed, partners-contribution

#266 #186: Extend the new Magento 2 module generation with the ability to …
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/generation/php/MagentoModuleGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleXml.java
  testData/actions/generation/generator/ModuleXmlGenerator/generateFileInRoot/module.xml
  testData/actions/generation/generator/ModuleXmlGenerator/generateModuleFile/module.xml
  testData/actions/generation/generator/ModuleXmlGeneratorHaveSetupVersion/generateModuleFile/module.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorHaveSetupVersionTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java
Labels: Award: bug fix, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#485 Fixed null pointer on the copy path action
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#487 Added new entity layout file generation, test for generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento New Entity Layout XML.xml.ft
  resources/fileTemplates/internal/Magento New Entity Layout XML.xml.html
  src/com/magento/idea/magento2plugin/actions/generation/data/NewEntityLayoutData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/NewEntityLayoutGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/NewEntityLayoutFile.java
  testData/actions/generation/generator/NewEntityLayoutGenerator/generateNewEntityLayoutFile/book_book_new.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/NewEntityLayoutGeneratorTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Atwix, partners-contribution

#350 #issue-179 Added email template generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Module Email Template Xml.xml.ft
  resources/fileTemplates/code/Magento Module Email Template Xml.xml.html
  resources/fileTemplates/internal/Magento Module Email Template Html.html.ft
  resources/fileTemplates/internal/Magento Module Email Template Html.html.html
  resources/fileTemplates/internal/Magento Module Email Templates Xml.xml.ft
  resources/fileTemplates/internal/Magento Module Email Templates Xml.xml.html
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/EmailTemplateHtmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/EmailTemplatesXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/dialog/NewEmailTemplateDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplateHtmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplatesXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEmailTemplatesXml.java
  src/com/magento/idea/magento2plugin/magento/files/EmailTemplateHtml.java
  src/com/magento/idea/magento2plugin/magento/files/EmailTemplatesXml.java
  src/com/magento/idea/magento2plugin/magento/packages/Package.java
  testData/actions/generation/generator/ModuleEmailTemplateHtmlGenerator/generateEmailTemplateHtml/custom_email_template_html.html
  testData/actions/generation/generator/ModuleEmailTemplateHtmlGenerator/generateEmailTemplateText/custom_email_template_text.html
  testData/actions/generation/generator/ModuleEmailTemplatesXmlGenerator/addTwoEmailTemplatesToEmailTemplatesXmlFile/email_templates.xml
  testData/actions/generation/generator/ModuleEmailTemplatesXmlGenerator/generateEmailTemplateHtmlXml/email_templates.xml
  testData/actions/generation/generator/ModuleEmailTemplatesXmlGenerator/generateEmailTemplateTextXml/email_templates.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplateHtmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplatesXmlGeneratorTest.java
Labels: Award: advanced, Award: category of expertise, Award: test coverage, Event: MageCONF CD 2020, Partner: Atwix, Progress: approved, partners-contribution

#486 3.1.1 >3.2.0 forwardport
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#490 Changed boolean field view on the form, converted labels for fields
  resources/fileTemplates/code/Magento Module UI Component Form Field Xml.xml.ft
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/magento/packages/uiComponent/FormElementType.java
Labels: Partner: Atwix, Progress: approved, QA passed, partners-contribution

#489 Fixed data provider to work with listing and form
  resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
  resources/fileTemplates/internal/Magento UI Component Form XML.xml.ft
  testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
Labels: Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#492 Added Generator Delete Entity By Id
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Delete Entity By Id Command.php.ft
  resources/fileTemplates/internal/Magento Delete Entity By Id Command.php.html
  src/com/magento/idea/magento2plugin/actions/generation/data/DeleteEntityByIdCommandData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityByIdCommandGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/commands/DeleteEntityByIdCommandFile.java
  src/com/magento/idea/magento2plugin/magento/packages/code/ExceptionType.java
  testData/actions/generation/generator/DeleteEntityCommandGenerator/generateDeleteEntityByIdCommandFile/DeleteByIdCommand.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityCommandGeneratorTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#488 464: fixed reference navigation for classes under directories with underscores
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  testData/project/magento2/vendor/magento/module-catalog/test_event/TestObserver.php
  testData/reference/xml/ObserverReferenceRegistrar/observerInstanceDirectorySnakeCaseMustHaveReference/events.xml
  tests/com/magento/idea/magento2plugin/reference/xml/ObserverReferenceRegistrarTest.java
Labels: Award: bug fix, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#496 495: Fixed the array access exception when using copy path
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#497 Forwardport 3.1.2 >3.2.0
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
  src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  testData/project/magento2/vendor/magento/module-catalog/test_event/TestObserver.php
  testData/reference/xml/ObserverReferenceRegistrar/observerInstanceDirectorySnakeCaseMustHaveReference/events.xml
  tests/com/magento/idea/magento2plugin/reference/xml/ObserverReferenceRegistrarTest.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution
