Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-01, with the labels that each got.

#447 Issue 443
  resources/fileTemplates/internal/Magento Preference Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/PreferenceFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  testData/actions/generation/generator/PreferenceClassGenerator/generatePreferenceInterfaceFile/InterfaceOverride.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGeneratorTest.java
Labels: Award: bug fix, Award: category of expertise, Award: test coverage, Partner: EY, partners-contribution

#448 445: Covered the NoninterceptableInterface case by plugin inspection …
  CHANGELOG.md
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/util/PhpClassImplementsNoninterceptableInterfaceUtil.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethod.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethodUtil.java
  testData/inspections/php/PluginInspection/withNoninterceptableTargetClass/Plugin.php
  testData/project/magento2/app/code/Foo/Bar/Model/NoninterceptableModel.php
  testData/project/magento2/vendor/magento/framework/ObjectManager/NoninterceptableInterface.php
  testData/project/magento2/vendor/magento/module-backend/etc/di.xml
  tests/com/magento/idea/magento2plugin/inspections/php/PluginInspectionTest.java
Labels: Award: bug fix, Award: special achievement, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#449 3.0.4 >3.1.0 forwardport
  CHANGELOG.md
  resources/fileTemplates/internal/Magento Preference Class.php.ft
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/data/PreferenceFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/php/util/PhpClassImplementsNoninterceptableInterfaceUtil.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethod.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethodUtil.java
  testData/actions/generation/generator/PreferenceClassGenerator/generatePreferenceInterfaceFile/InterfaceOverride.php
  testData/inspections/php/PluginInspection/withNoninterceptableTargetClass/Plugin.php
  testData/project/magento2/app/code/Foo/Bar/Model/NoninterceptableModel.php
  testData/project/magento2/vendor/magento/framework/ObjectManager/NoninterceptableInterface.php
  testData/project/magento2/vendor/magento/module-backend/etc/di.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGeneratorTest.java
  tests/com/magento/idea/magento2plugin/inspections/php/PluginInspectionTest.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#451 Added CopyMagentoPath action
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: Award: complex, Partner: EY, Progress: approved, partners-contribution

#453 309 add declarative schema generation
  gradle-tasks/pmd/ruleset.xml
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Declarative Schema XML.xml.ft
  resources/fileTemplates/internal/Magento Module Declarative Schema XML.xml.html
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DbSchemaXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ui/ComboBoxItemData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/HighlightDialogFieldOnErrorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/TableNameLength.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaXmlUtil.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaXml.java
  src/com/magento/idea/magento2plugin/magento/packages/database/TableColumnTypes.java
  src/com/magento/idea/magento2plugin/magento/packages/database/TableEngines.java
  src/com/magento/idea/magento2plugin/magento/packages/database/TableResources.java
  src/com/magento/idea/magento2plugin/ui/table/ComboBoxCellEditor.java
  src/com/magento/idea/magento2plugin/ui/table/TableGroupWrapper.java
  testData/actions/generation/generator/DbSchemaXmlGenerator/generateDbSchemaXmlFile/db_schema.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGeneratorTest.java
Labels: Award: advanced, Award: category of expertise, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#455 Update readme
  README.md
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#456 Initial implementation of entity manager (MVP)
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/NewEntityAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DbSchemaXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/util/DbSchemaXmlSourceDataUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueryGenerator.java
  src/com/magento/idea/magento2plugin/magento/packages/PropertiesTypes.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#458 309 add db schema whitelist generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Declarative Schema Whitelist JSON.json.ft
  resources/fileTemplates/internal/Magento Module Declarative Schema Whitelist JSON.json.html
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaWhitelistJson.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaWhitelistJson.java
  testData/actions/generation/generator/DbSchemaWhitelistGenerator/generateDbSchemaWhitelistJsonFile/db_schema_whitelist.json
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistGeneratorTest.java
Labels: Award: advanced, Award: test coverage, Partner: Atwix, Progress: approved, in testing, partners-contribution

#459 Provide declarative schema features to entity manager
  src/com/magento/idea/magento2plugin/actions/generation/data/DbSchemaXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/util/DbSchemaXmlSourceDataUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/DbSchemaGeneratorUtil.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaXml.java
  src/com/magento/idea/magento2plugin/magento/packages/PropertiesTypes.java
  src/com/magento/idea/magento2plugin/magento/packages/database/ColumnAttributes.java
  src/com/magento/idea/magento2plugin/magento/packages/database/PropertyToDefaultTypeMapperUtil.java
  src/com/magento/idea/magento2plugin/reference/provider/TableColumnNamesReferenceProvider.java
  testData/actions/generation/generator/DbSchemaWhitelistGenerator/generateDbSchemaWhitelistJsonFileForShortProperties/db_schema_whitelist.json
  testData/actions/generation/generator/DbSchemaXmlGenerator/generateDbSchemaXmlFileForShortProperties/db_schema.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/util/DbSchemaGeneratorDataProviderUtil.java
Labels: Award: complex, Partner: Atwix, Progress: review, partners-contribution

#460 Added templates descriptions for Magento Data Model and Magento Data Model Interface
  resources/fileTemplates/internal/Magento Data Model Interface.php.html
  resources/fileTemplates/internal/Magento Data Model.php.html
Labels: Partner: Atwix, partners-contribution

#462 Add query service generation and providing it to data provider
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Get List Query Model.php.ft
  resources/fileTemplates/internal/Magento Get List Query Model.php.html
  resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/GetListQueryModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentDataProviderData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/GetListQueryModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentDataProviderPhp.java
  src/com/magento/idea/magento2plugin/magento/files/queries/GetListQuery.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/actions/generation/generator/QueryModelGenerator/generateGetListQueryModelFile/GetListQuery.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueryModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution
