Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-04, with the labels that each got.

#524 Enhabced validation, added filtering for fields to validate on entity…
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/reflection/ExtractComponentFromFieldUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/reflection/GetReflectionFieldUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/DialogFieldErrorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/FieldValidation.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/TypeFieldsRulesParser.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/ValidationMessageExtractorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/ValidationRuleExtractorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/data/FieldValidationData.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/pool/provider/NewEntityGeneratorsProviderUtil.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#527 Created Product attribute setup patch generator
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/NewEavAttributeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/EavEntityDataInterface.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/AttributeMapperFactory.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/AttributeMapperInterface.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java
  src/com/magento/idea/magento2plugin/magento/files/EavAttributeDataPatchPhp.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeInputs.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeScopes.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeSourceModels.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeTypes.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/DataPatchDependency.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttributes.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavEntities.java
  testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFile/AddTestAttribute.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, Progress: on hold, partners-contribution

#529 Fixed incorrect duplication warning for disabled plugin in di.xml
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#530 Updated plugin logo
  resources/META-INF/pluginIcon.svg
  resources/META-INF/pluginIcon_dark.svg
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#533 Fixed error when plugin or observer name is not set
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#536 JS and CSS support for Copy Magento Path action
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: Award: complex, Partner: EY, Progress: approved, partners-contribution

#540 539 add apply to property
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/data/EavEntityDataInterface.java
  src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/ApplyToVisibleListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/CommaSeparatedStringRule.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/magento/files/ProductTypeXml.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttribute.java
  src/com/magento/idea/magento2plugin/stubs/indexes/xml/ProductTypeIndex.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetProductTypesListUtil.java
  testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java
Labels: Award: advanced, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#553 Fixed error with builds in CI for the project
  gradle-tasks/staticChecks.gradle
Labels: Award: bug fix, Award: category of expertise, Partner: Atwix, Progress: approved, partners-contribution

#546 Added possibility to set options
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/AttributeSourcePanelComponentListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/AttributeSourceRelationsItemListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/OptionsPanelVisibilityChangeListener.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetAttributeOptionPropertiesUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeSourceModel.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttribute.java
  testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#554 Completely removed unknown property for pmd extension
  gradle-tasks/staticChecks.gradle
Labels: Partner: Atwix, Progress: approved, partners-contribution

#555 Update version in readme
  README.md
Labels: Progress: approved

#549 Fixed entity data mapper file template position
  resources/fileTemplates/internal/Magento Entity Data Mapper.php.ft
  resources/fileTemplates/internal/Magento Entity Data Mapper.php.html
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#561 560 eav attribute generation refactoring
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/ApplyToVisibleListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/AttributeSourcePanelComponentListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/AttributeSourceRelationsItemListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/DataPatchNameAdapter.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/EavAttributeInputItemListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/OptionsPanelVisibilityChangeListener.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/SourceModelNameAdapter.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/SplitEavAttributeCodeUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/eavdialog/AttributeUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/eavattribute/NewEavAttributeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/eavattribute/NewProductEavAttributeAction.java
  src/com/magento/idea/magento2plugin/actions/groups/NewEavAttributeGroup.java
Labels: Award: special achievement, Progress: review

#552 Developed error handler that help user to create new bug report
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/GitHub New Bug Issue Body Template.txt.ft
  resources/fileTemplates/code/GitHub New Bug Issue Body Template.txt.html
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/project/diagnostic/DefaultErrorReportSubmitter.java
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueUrlBuilderUtil.java
Labels: Award: complex, Partner: Atwix, Progress: approved, partners-contribution

#562 Add new rule for check copyright in files
  gradle-tasks/checkstyle/checkstyle.xml
Labels: Award: category of expertise, Progress: ready for review

#544 Fixed bugs tables editing
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#548 Developed web api xml file generation, web api xml declaration generation, improved action development experience, added PhpPsiElementsUtil
  resources/META-INF/plugin.xml
  resources/fileTemplates/code/Magento Web Api Declaration.xml.ft
  resources/fileTemplates/code/Magento Web Api Declaration.xml.html
  resources/fileTemplates/internal/Magento Web Api XML.xml.ft
  resources/fileTemplates/internal/Magento Web Api XML.xml.html
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewWebApiDeclarationAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/xml/WebApiXmlRouteData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewWebApiDeclarationDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewWebApiDeclarationDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithForwardSlash.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/xml/WebApiDeclarationGenerator.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleWebApiXmlFile.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoPhpClass.java
  src/com/magento/idea/magento2plugin/magento/packages/WebApiResource.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethodUtil.java
  src/com/magento/idea/magento2plugin/util/php/PhpPsiElementsUtil.java
  testData/actions/generation/generator/WebApiXmlDeclarationGenerator/generateWebApiXmlDeclarationForService/webapi.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/WebApiXmlDeclarationGeneratorTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#564 Changed intellij version to the latest version
  build.gradle
Labels: Progress: ready for review

#557 Fixed copyrights, indentation and added @NotNull to methods
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/dialog/NewEmailTemplateDialogValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AclResourceIdRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphaWithDashRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphaWithPeriodRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphanumericRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AlphanumericWithUnderscoreRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/BoxNotEmptyRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/CliCommandRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/ConfigPathRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/CronScheduleRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/DirectoryRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithColonRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/Lowercase.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/MenuIdentifierRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/NotEmptyRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/NumericRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpClassFqnRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpClassRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpDirectoryRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpNamespaceNameRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/RouteIdRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/StartWithNumberOrCapitalLetterRule.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/TableNameLength.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormButtonsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsValidator.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java
Labels: Progress: approved

#565 Fixed the bug of creating a subdirectory
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpDirectoryRule.java
Labels: Progress: approved

#570 3.2.1 >4.0.0 forwardport
  CHANGELOG.md
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#575 Multiple improvements to EAV generators
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavEntity.java
  testData/actions/generation/generator/CategoryAttributePropertySetupPatchGenerator/generateFile/AddTestAttributeCategoryAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFile/AddTestAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#571 Fixed namespace in controller
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
Labels: Partner: Atwix, Progress: ready for review, partners-contribution

#573 Added logic for validation only visible fields on the dialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#574 Refactored and improved EAV attribute generators
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/AttributeCodeAdapter.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#577 Web API XML service tag inspection
  resources/META-INF/plugin.xml
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/MagentoIcons.java
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/AclResourceXmlInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/WebApiServiceInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/fix/MethodNotPublicAccessQuickFix.java
  src/com/magento/idea/magento2plugin/magento/files/AbstractPhpFile.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleWebApiXmlFile.java
  src/com/magento/idea/magento2plugin/magento/files/Plugin.java
  src/com/magento/idea/magento2plugin/util/magento/plugin/IsPluginAllowedForMethodUtil.java
  testData/inspections/xml/WebApiServiceInspection/existentClass/webapi.xml
  testData/inspections/xml/WebApiServiceInspection/existentMethod/webapi.xml
  testData/inspections/xml/WebApiServiceInspection/notExistentClass/webapi.xml
  testData/inspections/xml/WebApiServiceInspection/notExistentMethod/webapi.xml
  testData/inspections/xml/WebApiServiceInspection/notPublicMethod/webapi.xml
  testData/inspections/xml/WebApiServiceInspection/publicMethod/webapi.xml
  testData/project/magento2/app/code/Foo/Bar/Service/SimpleService.php
  tests/com/magento/idea/magento2plugin/inspections/xml/AclResourceXmlInspectionTest.java
  tests/com/magento/idea/magento2plugin/inspections/xml/WebApiServiceInspectionTest.java
Labels: Award: advanced, Award: test coverage, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#581 Fixed wrong new entity layout name and edit entity layout name inside it
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Partner: Atwix, Progress: review, partners-contribution

#580 Fixed `Java.lang.IllegalArgumentException` During adding a new method…
  CHANGELOG.md
  resources/META-INF/pluginIcon.svg
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#582 Develop types inspections inside type tag
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/InvalidDiTypeInspection.html
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/validator/InspectionValidator.java
  src/com/magento/idea/magento2plugin/inspections/validator/NotEmptyValidator.java
  src/com/magento/idea/magento2plugin/inspections/validator/PhpClassExistenceValidator.java
  src/com/magento/idea/magento2plugin/inspections/validator/VirtualTypeExistenceValidator.java
  src/com/magento/idea/magento2plugin/inspections/xml/InvalidDependencyInjectionTypeInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/WebApiServiceInspection.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java
  testData/inspections/xml/TypeConfigurationTagTypesInspection/argumentFactoryTypeExists/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/nameAttributeValueTypeDoesNotExist/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/nameAttributeValueTypeExists/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/recursivelyArgumentProxyTypeDoesNotExist/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/recursivelyArgumentProxyTypeExists/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/recursivelyArgumentVirtualTypeDoesNotExist/di.xml
  testData/inspections/xml/TypeConfigurationTagTypesInspection/recursivelyArgumentVirtualTypeExists/di.xml
  testData/project/magento2/app/code/Foo/Bar2/composer.json
  testData/project/magento2/app/code/Foo/Bar2/etc/di.xml
  testData/project/magento2/app/code/Foo/Bar2/etc/module.xml
  testData/project/magento2/app/code/Foo/Bar2/registration.php
  tests/com/magento/idea/magento2plugin/inspections/xml/TypeConfigurationTagTypesInspectionTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution
