Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-03, with the labels that each got.

#493 Added Generator for Delete Controller
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Entity Delete Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Delete Controller Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/data/DeleteEntityControllerFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/actions/DeleteActionFile.java
  testData/actions/generation/generator/DeleteEntityGenerator/generateDeleteEntityFile/Delete.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityGeneratorTest.java
Labels: Award: special achievement, Award: test coverage, Partner: Atwix, Progress: review, on hold, partners-contribution

#499 Require restart
  CHANGELOG.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormButtonPhpClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateAclXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCronGroupXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCrontabXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaWhitelistJson.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaXmlUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDiXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEventsXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateLayoutXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateMenuXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateRoutesXml.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: Award: bug fix, Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#505 502: Fixed - Class completion doesn't display interfaces.
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/completion/provider/PhpClassCompletionProvider.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#504 Fixed bug invalid check setup_version
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java
  testData/inspections/xml/ModuleDeclarationInModuleXmlInspection/setupVersionNotErrorMessageInEditableModule/app/code/Test/TestModule/etc/module.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspectionTest.java
Labels: Award: bug fix, Award: test coverage, Partner: Atwix, partners-contribution

#506 Entity manager capitalized entity name
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#511 Enhanced UX with generation process, generation in the separate thread (non-blocking UI), fixed multiple action listener firing
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/ProcessWorker.java
Labels: Award: advanced, Partner: Atwix, Progress: approved, QA passed, partners-contribution

#513 Forward port 3.1.3 develop >3.2.0 develop
  CHANGELOG.md
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplateHtmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleRegistrationPhpGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormButtonPhpClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateAclXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCronGroupXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCrontabXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaWhitelistJson.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaXmlUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDiXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEmailTemplatesXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEventsXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateLayoutXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateMenuXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateRoutesXml.java
  src/com/magento/idea/magento2plugin/completion/provider/PhpClassCompletionProvider.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java
  testData/inspections/xml/ModuleDeclarationInModuleXmlInspection/setupVersionNotErrorMessageInEditableModule/app/code/Test/TestModule/etc/module.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspectionTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#514 Enhanced and refactored bunch of generators and all related files and their testcases
  src/com/magento/idea/magento2plugin/actions/generation/data/DataModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DataModelInterfaceData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/EntityDataMapperData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/GetListQueryModelData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/IndexActionData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/PreferenceDiXmFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentDataProviderData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/DataModelDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/DataModelInterfaceDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/DataProviderDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/EntityDataMapperDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/GetListQueryDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/IndexActionDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/PreferenceDiXmlFileDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/GetListQueryModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/IndexActionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueryGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/pool/handler/DataModelInterfaceGeneratorHandler.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/pool/handler/IndexActionGeneratorHandler.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/pool/provider/NewEntityGeneratorsProviderUtil.java
  src/com/magento/idea/magento2plugin/magento/files/DataModelFile.java
  src/com/magento/idea/magento2plugin/magento/files/EntityDataMapperFile.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentDataProviderFile.java
  src/com/magento/idea/magento2plugin/magento/files/actions/IndexActionFile.java
  src/com/magento/idea/magento2plugin/magento/files/queries/GetListQueryFile.java
  testData/actions/generation/generator/IndexControllerGenerator/generateIndexControllerFile/Index.php
  testData/actions/generation/generator/QueryModelGenerator/generateGetListQueryModelFile/GetListQuery.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperClassGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/IndexControllerGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/QueryModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#515 Focusing the entity name field after opening the Entity dialog
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Award: bug fix, Partner: Atwix, Progress: review, partners-contribution

#516 Validation enhanced to show all errors above the fields on the form
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/DialogFieldErrorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/HighlightDialogFieldOnErrorUtil.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution

#517 Refactored entity creator generators, removed unnecessary namespace builders from dto
  src/com/magento/idea/magento2plugin/actions/generation/data/DeleteEntityByIdCommandData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/DeleteEntityControllerFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/EditEntityActionData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/FormGenericButtonBlockData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityCommandData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityControllerFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentFormFileData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/DeleteEntityByIdCommandDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/FormDeleteControllerDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/FormEditControllerDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/FormGenericButtonBlockDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/FormSaveControllerDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/SaveEntityCommandDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/UiComponentFormLayoutDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/UiComponentGridDtoConverter.java
  src/com/magento/idea/magento2plugin/actions/generation/data/dialog/EntityCreatorContextData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/dialog/GenerationContextData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityByIdCommandGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/pool/GeneratorHandler.java
  src/com/magento/idea/magento2plugin/magento/files/FormGenericButtonBlockFile.java
  src/com/magento/idea/magento2plugin/magento/files/ModelFile.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentFormXmlFile.java
  src/com/magento/idea/magento2plugin/magento/files/UiComponentGridXmlFile.java
  src/com/magento/idea/magento2plugin/magento/files/actions/DeleteActionFile.java
  src/com/magento/idea/magento2plugin/magento/files/actions/EditActionFile.java
  src/com/magento/idea/magento2plugin/magento/files/actions/SaveActionFile.java
  src/com/magento/idea/magento2plugin/magento/files/commands/DeleteEntityByIdCommandFile.java
  src/com/magento/idea/magento2plugin/magento/files/commands/SaveEntityCommandFile.java
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
  testData/actions/generation/generator/SaveEntityCommandGenerator/generateSaveEntityCommandFile/SaveCommand.php
  testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityCommandGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityActionGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/pool/NewEntityGeneratorPoolTest.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#519 Error in the console (New Module Action)
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: Award: bug fix, Award: special achievement, Progress: approved

#518 Added navigation to tab with error on field
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Award: special achievement, Partner: Atwix, Progress: approved, partners-contribution
