Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-05, with the labels that each got.

#585 Forwardport 3 2 2 >4 0 0
  CHANGELOG.md
  resources/META-INF/pluginIcon.svg
  src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: Cleanup, Partner: Atwix, Progress: approved, partners-contribution

#578 Developed preference xml inspections
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/PreferenceXmlInspections.html
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/InvalidDependencyInjectionTypeInspection.java
  src/com/magento/idea/magento2plugin/inspections/xml/PreferenceDeclarationInspection.java
  testData/inspections/xml/PreferenceDeclarationInspection/attrArgForValueIsEmpty/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/attrArgTypeValueIsEmpty/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/attrForClassExists/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/attrTypeClassExists/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/classAttrForDoesNotExists/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/classAttrForIsExist/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/classAttrTypeDoesNotExists/di.xml
  testData/inspections/xml/PreferenceDeclarationInspection/classAttrTypeIsExist/di.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/PreferenceDeclarationInspectionTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, QA failed, partners-contribution

#592 Fixed issue with too long URI for generated bug report by diagnostic feature
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/project/diagnostic/DefaultErrorReportSubmitter.java
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueUrlBuilderUtil.java
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#587 Fixing the EAV selected scope for the generated attributes
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/eavdialog/AttributeUtil.java
  testData/actions/generation/generator/CategoryAttributePropertySetupPatchGenerator/generateFile/AddTestAttributeCategoryAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFile/AddTestAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
Labels: Partner: Atwix, Progress: review, partners-contribution

#593 Diagnostic improvement
  resources/fileTemplates/code/GitHub New Bug Issue Body Template.txt.ft
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
Labels: Partner: Atwix, Progress: approved, partners-contribution

#588 Develop plugin declaration inspections
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/PluginAttrTypeInspection.html
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/PluginAttributeTypeInspection.java
  testData/inspections/xml/PluginAttributeTypeInspection/attrArgTypeValueIsEmpty/di.xml
  testData/inspections/xml/PluginAttributeTypeInspection/attrTypeClassExists/di.xml
  testData/inspections/xml/PluginAttributeTypeInspection/classAttrTypeDoesNotExists/di.xml
  testData/inspections/xml/PluginAttributeTypeInspection/classAttrTypeIsExist/di.xml
  tests/com/magento/idea/magento2plugin/inspections/xml/PluginAttributeTypeInspectionTest.java
Labels: Award: complex, Award: test coverage, Partner: Atwix, Progress: approved, partners-contribution

#591 Simplified file properties definition for the php file generation
  src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityByIdCommandGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/GetListQueryModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/IndexActionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/NewActionEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PhpFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityControllerFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/php/WebApiInterfaceGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassGeneratorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassTypesBuilder.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: Award: advanced, Partner: Atwix, Progress: review, partners-contribution
