Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-12, with the labels that each got.

#819 [Bug] 626: Fixed Invalid column types provided exception during db_schema.xml file generation
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGenerator.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#830 Bugfix/630 method designed for fully qualified names only
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/util/ConvertPluginParamsToString.java
  src/com/magento/idea/magento2plugin/actions/generation/references/PhpClassReferenceExtractor.java
  src/com/magento/idea/magento2plugin/actions/generation/references/PhpClassReferenceResolver.java
  src/com/magento/idea/magento2plugin/actions/generation/references/PhpClassReferenceStorage.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#831 [Release-4.2.1] Preparing release 4 2 1
  CHANGELOG.md
Labels: partners-contribution, Partner: Atwix, Progress: approved, release-4.2.1

#849 797: plugin inspection null pointer exception
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#850 838: Fixed java.lang.NoClassDefFoundError for com.intellij.lang.jsgraphql.GraphQLIcons
  build.gradle
  src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#851 Additional changes before 4.2.1 release
  CHANGELOG.md
Labels: partners-contribution, Partner: Atwix, Progress: approved

#852 810: Fixed StringIndexOutOfBoundsException during UCT inspection via action execution
  src/com/magento/idea/magento2uct/util/php/MagentoTypeEscapeUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#848 698: Add "module" prefix to module name in composer.json
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFileWithoutDependencies/composer.json
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Award: test coverage

#854 837: Fixed wrong connection name
  src/com/magento/idea/magento2plugin/magento/packages/MessageQueueConnections.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#844 633: Fixed NoSuchElementException when creating new controller
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CLICommandClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleEmailTemplateHtmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/NewEntityLayoutGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PhpFileGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/QueryGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormButtonBlockGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateAclXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCronGroupXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateCrontabXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaWhitelistJson.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaXmlUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDiXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEmailTemplatesXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateEventsXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateLayoutXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateMenuXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateQueueXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateRoutesXml.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/xml/WebApiDeclarationGenerator.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Award: special achievement, Progress: approved, Award: category of expertise

#856 825: null pointer exception new cronjob dialog suggest cronjob name
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#859 858: error correction in case entered fields is zero
  src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: category of expertise

#860 760: fixed throwable when io exception is thrown during plugin generation
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: category of expertise

#862 651: slow operations are prohibited on EDT
  src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
  src/com/magento/idea/magento2plugin/inspections/php/util/PhpClassImplementsNoninterceptableInterfaceUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: category of expertise

#885 872: enhanced new cli command dialog UX
  src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewCLICommandAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewViewModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#892 879 enhance new UI form dialog ux
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentFormAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentGridAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#893 857: fixed error when class already exists
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#894 842 incomplete trailing escape
  src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java
  src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#896 866: IndexNotReadyException while opening a context menu
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: review

#897 654: fixed class cast exception in web api type index
  src/com/magento/idea/magento2plugin/stubs/indexes/WebApiTypeIndex.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#898 834: module name declaration inspection flags valid code
  src/com/magento/idea/magento2plugin/inspections/php/ModuleDeclarationInRegistrationPhpInspection.java
  src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
  testData/project/magento2/vendor/magento/framework/Component/ComponentRegistrar.php
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#902 590: The plugin inspection does not work correctly
  src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved
