Repository magento/magento2-phpstorm-plugin, pull requests merged in 2021-11, with the labels that each got.

#662 [4.1.1-develop] Bug-653: Fixed NullPointerException for InjectAViewModelAction#getElement
  src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#661 [4.1.1-develop] Fixed Bug with inspection observer null pointer for event name attribute
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#740 [UCT] Developed Existence index
  src/com/magento/idea/magento2uct/execution/ReindexUctCommand.java
  src/com/magento/idea/magento2uct/execution/process/ReindexHandler.java
  src/com/magento/idea/magento2uct/packages/IndexRegistry.java
  src/com/magento/idea/magento2uct/ui/ReindexDialog.form
  src/com/magento/idea/magento2uct/ui/ReindexDialog.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
  src/com/magento/idea/magento2uct/versioning/indexes/IndexRepository.java
  src/com/magento/idea/magento2uct/versioning/indexes/Storage.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/DeprecationStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ExistenceStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/VersionStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/storage/FileLoader.java
  src/com/magento/idea/magento2uct/versioning/indexes/storage/FileWriter.java
  src/com/magento/idea/magento2uct/versioning/indexes/storage/IndexLoader.java
  src/com/magento/idea/magento2uct/versioning/indexes/storage/IndexWriter.java
  src/com/magento/idea/magento2uct/versioning/indexes/storage/ResourceLoader.java
  src/com/magento/idea/magento2uct/versioning/processors/DeprecationIndexProcessor.java
  src/com/magento/idea/magento2uct/versioning/processors/ExistenceIndexProcessor.java
  src/com/magento/idea/magento2uct/versioning/processors/IndexProcessor.java
  src/com/magento/idea/magento2uct/versioning/processors/PhpClassLocatorUtil.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Award: advanced, Award: special achievement, Progress: approved, Award: category of expertise, Upgrade Compatibility Tool

#747 UCT-687: Enhanced Magento 2 version resolved
  src/com/magento/idea/magento2plugin/magento/files/ComposerLock.java
  src/com/magento/idea/magento2plugin/magento/packages/code/MagentoVersion.java
  src/com/magento/idea/magento2plugin/project/util/GetMagentoVersionUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Award: special achievement, Progress: approved, Award: category of expertise, Upgrade Compatibility Tool

#751 Update Platform Version In Setting Form
  src/com/magento/idea/magento2plugin/magento/packages/code/MagentoVersion.java
  src/com/magento/idea/magento2plugin/project/Settings.java
  src/com/magento/idea/magento2plugin/project/SettingsForm.form
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
  src/com/magento/idea/magento2plugin/project/util/GetMagentoVersionUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
Labels: Award: complex, partners-contribution, Partner: Atwix, in testing, Progress: approved, Award: category of expertise

#754 UCT-711: Developed ImportingNonExistentInterface inspection
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ImportingNonExistentInterface.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/existence/ImportingNonExistentInterface.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Upgrade Compatibility Tool

#777 Automatically detect version and platform
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
Labels: partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise

#778 UCT-722: Inspection imported non api class
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ImportedNonApiClass.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/ImportedNonApiClass.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ApiCoverageStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/DeprecationStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ExistenceStateIndex.java
  src/com/magento/idea/magento2uct/versioning/processors/util/VersioningDataOperationsUtil.java
Labels: inspection, Award: complex, partners-contribution, Partner: Atwix, Award: special achievement, Award: category of expertise, Upgrade Compatibility Tool

#779 UCT-723: Added ImportedNonApiInterface inspection
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ImportedNonApiInterface.html
  resources/uct/api/indexes.API_COVERAGE.idc
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/ImportInspection.java
  src/com/magento/idea/magento2uct/inspections/php/api/ImportedNonApiInterface.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ApiCoverageStateIndex.java
  src/com/magento/idea/magento2uct/versioning/processors/util/VersioningDataOperationsUtil.java
Labels: inspection, Award: complex, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise, Upgrade Compatibility Tool

#784 UCT-774: Rephrased messages for deprecations
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/deprecation/CallingDeprecatedMethod.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ExtendingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImplementedDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/InheritedDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedConstant.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedProperty.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedConstant.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedProperty.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/DeprecationStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ExistenceStateIndex.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise, Upgrade Compatibility Tool

#786 UCT-768: Sort errors by lines
  src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
  src/com/magento/idea/magento2uct/execution/output/Summary.java
  src/com/magento/idea/magento2uct/inspections/UctInspectionManager.java
  src/com/magento/idea/magento2uct/settings/UctSettingsService.java
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
  src/com/magento/idea/magento2uct/util/inspection/SortDescriptorResultsUtil.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Upgrade Compatibility Tool

#787 UCT-782: Added alternative UCT module name
  src/com/magento/idea/magento2uct/util/module/UctModuleLocatorUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Upgrade Compatibility Tool

#789 UCT-730: Added inspection CalledNonApiMethod
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/CalledNonApiMethod.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/CalledNonApiMethod.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Progress: approved, Upgrade Compatibility Tool

#790 UCT-728,729: Inspection overridden non api constant or property
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/OverriddenNonApiConstant.html
  resources/inspectionDescriptions/OverriddenNonApiProperty.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/OverriddenNonApiConstant.java
  src/com/magento/idea/magento2uct/inspections/php/api/OverriddenNonApiProperty.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Upgrade Compatibility Tool

#791 UCT-726-727: Added inspections: UsedNonApiConstant, UsedNonApiProperty
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/UsedNonApiConstant.html
  resources/inspectionDescriptions/UsedNonApiProperty.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiConstant.java
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiProperty.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Upgrade Compatibility Tool

#792 UCT-725: Developed used non api reference inspection, added factory and proxy types support
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/UsedNonApiType.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/UsedTypeInspection.java
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiType.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
  src/com/magento/idea/magento2uct/util/php/MagentoTypeEscapeUtil.java
  src/com/magento/idea/magento2uct/util/php/ReferenceResolverUtil.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: advanced, Progress: approved, Upgrade Compatibility Tool

#793 UCT-720-724: inspection extended implemented non api inspections
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ExtendedNonApiClass.html
  resources/inspectionDescriptions/ImplementedNonApiInterface.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/ExtendedNonApiClass.java
  src/com/magento/idea/magento2uct/inspections/php/api/ImplementedNonApiInterface.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Upgrade Compatibility Tool

#794 UCT-719: inspection inherited non api interface
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/InheritedNonApiInterface.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/InheritedNonApiInterface.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Progress: approved, Upgrade Compatibility Tool

#795 UCT-718: Added inspection about possible dependency on implementation details
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/PossibleDependencyOnImplDetails.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/PossibleDependencyOnImplDetails.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
Labels: inspection, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Upgrade Compatibility Tool

#796 UCT-731: Added inspection call non-interface method
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/CalledNonInterfaceMethod.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/inspections/php/api/CalledNonInterfaceMethod.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/DeprecationStateIndex.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ExistenceStateIndex.java
Labels: inspection, Award: complex, partners-contribution, Partner: Atwix, Upgrade Compatibility Tool

#800 [4.2.0-develop] Bug-653: Fixed NullPointerException for InjectAViewModelAction#getElement
  src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Cleanup

#799 [4.2.0-develop] Bug-659: Fixed NullPointerException for a name attribute of the event tag and code style fixes
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Cleanup

#801 [4.2.0-develop] Bug-663: Fixed NullPointerException for PluginReferenceProvider
  src/com/magento/idea/magento2plugin/reference/provider/PluginReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Cleanup

#802 UCT-766: Prioritised messages, code refactoring
  src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
  src/com/magento/idea/magento2uct/inspections/UctProblemsHolder.java
  src/com/magento/idea/magento2uct/inspections/php/api/CalledNonApiMethod.java
  src/com/magento/idea/magento2uct/inspections/php/api/CalledNonInterfaceMethod.java
  src/com/magento/idea/magento2uct/inspections/php/api/ExtendedNonApiClass.java
  src/com/magento/idea/magento2uct/inspections/php/api/ImplementedNonApiInterface.java
  src/com/magento/idea/magento2uct/inspections/php/api/ImportedNonApiClass.java
  src/com/magento/idea/magento2uct/inspections/php/api/ImportedNonApiInterface.java
  src/com/magento/idea/magento2uct/inspections/php/api/InheritedNonApiInterface.java
  src/com/magento/idea/magento2uct/inspections/php/api/OverriddenNonApiConstant.java
  src/com/magento/idea/magento2uct/inspections/php/api/OverriddenNonApiProperty.java
  src/com/magento/idea/magento2uct/inspections/php/api/PossibleDependencyOnImplDetails.java
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiConstant.java
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiProperty.java
  src/com/magento/idea/magento2uct/inspections/php/api/UsedNonApiType.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/CallingDeprecatedMethod.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ExtendingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImplementedDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/InheritedDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedConstant.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedProperty.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedClass.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedConstant.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedInterface.java
  src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedProperty.java
  src/com/magento/idea/magento2uct/inspections/php/existence/CalledNonExistentMethod.java
  src/com/magento/idea/magento2uct/inspections/php/existence/ExtendedNonExistentClass.java
  src/com/magento/idea/magento2uct/inspections/php/existence/ImplementedNonExistentInterface.java
  src/com/magento/idea/magento2uct/inspections/php/existence/ImportingNonExistentClass.java
  src/com/magento/idea/magento2uct/inspections/php/existence/ImportingNonExistentInterface.java
  src/com/magento/idea/magento2uct/inspections/php/existence/InheritedNonExistentInterface.java
  src/com/magento/idea/magento2uct/inspections/php/existence/OverriddenNonExistentConstant.java
  src/com/magento/idea/magento2uct/inspections/php/existence/OverriddenNonExistentProperty.java
  src/com/magento/idea/magento2uct/inspections/php/existence/UsedNonExistentConstant.java
  src/com/magento/idea/magento2uct/inspections/php/existence/UsedNonExistentProperty.java
  src/com/magento/idea/magento2uct/inspections/php/existence/UsedNonExistentType.java
  src/com/magento/idea/magento2uct/util/inspection/FilterDescriptorResultsUtil.java
Labels: enhancement, partners-contribution, Partner: Atwix, Award: advanced, Progress: approved, Upgrade Compatibility Tool

#805 Modified CHANGELOG before release 4.2.0
  CHANGELOG.md
Labels: partners-contribution, Partner: Atwix, Progress: review

#808 Bugfix-798: Fixed ArrayIndexOutOfBoundsException exception
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: bug, partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#811 Bug-667: Fixed dialog disposition issue
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewInterfaceForServiceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewWebApiDeclarationDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
  src/com/magento/idea/magento2uct/ui/ReindexDialog.java
Labels: bug, Award: complex, partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: category of expertise

#813 Bugfix/765: Fixed stack overflow error for line-marker providers
  src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java
  src/com/magento/idea/magento2plugin/linemarker/php/WebApiLineMarkerProvider.java
Labels: partners-contribution, Partner: Atwix, Award: advanced, Award: bug fix, Award: special achievement, Progress: approved

#814 [Bug] 666: Fixed stub ids not found for key in index
  src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: category of expertise

#815 Bugfix-645: Fixed failed to build require-js index
  src/com/magento/idea/magento2plugin/stubs/indexes/js/RequireJsIndex.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#816 Bugfix-739: Fixed empty psi elements in the plugin inspections
  src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#817 [Bugfix:685] Fixed empty psi element in module xml inspection
  src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#818 [Bug] 646: Fixed NullPointerException for the firstSortOrder.compareTo
  src/com/magento/idea/magento2plugin/linemarker/php/WebApiLineMarkerProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: review
