Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-12, with the labels that each got.

#1260 Constant visibility type declarations
  resources/fileTemplates/internal/Magento Backend Controller Class.php.ft
  resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft
  resources/fileTemplates/internal/Magento Data Model Interface.php.ft
  resources/fileTemplates/internal/Magento Data Model.php.ft
  resources/fileTemplates/internal/Magento Delete Entity By Id Command.php.ft
  resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
  resources/fileTemplates/internal/Magento Entity Data Mapper.php.ft
  resources/fileTemplates/internal/Magento Entity Delete Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Edit Action Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Index Adminhtml Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity New Action Controller Class.php.ft
  resources/fileTemplates/internal/Magento Entity Save Controller Class.php.ft
  resources/fileTemplates/internal/Magento Get List Query Model.php.ft
  resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.ft
  resources/fileTemplates/internal/Magento Module Setup Patch File.php.ft
  resources/fileTemplates/internal/Magento PHP Form Generic Button Block Class.php.ft
  resources/fileTemplates/internal/Magento Save Entity Command Model.php.ft
  resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
  testData/actions/generation/generator/CategoryAttributePropertySetupPatchGenerator/generateFile/AddTestAttributeCategoryAttribute.php
  testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
  testData/actions/generation/generator/DataModelGenerator/generateDataModelWithoutInterface/Sample.php
  testData/actions/generation/generator/DataModelInterfaceGenerator/generateDataModelInterface/SampleInterface.php
  testData/actions/generation/generator/DeleteEntityCommandGenerator/generateDeleteEntityByIdCommandFile/DeleteByIdCommand.php
  testData/actions/generation/generator/DeleteEntityGenerator/generateDeleteEntityFile/Delete.php
  testData/actions/generation/generator/EditEntityActionGenerator/generateEditEntityActionFile/Edit.php
  testData/actions/generation/generator/EntityDataMapperClassGenerator/generateEntityDataMapperFile/UnicornDataMapper.php
  testData/actions/generation/generator/FormGenericButtonBlockGenerator/generateFormGenericButtonBlockFile/GenericButton.php
  testData/actions/generation/generator/GridActionColumnFileGenerator/generateGridActionColumnFile/BookBlockActions.php
  testData/actions/generation/generator/IndexControllerGenerator/generateIndexControllerFile/Index.php
  testData/actions/generation/generator/ModuleControllerClassGenerator/generateBackendControllerFile/BackendSaveAction.php
  testData/actions/generation/generator/ModuleSetupDataPatchGenerator/generateModuleSetupDataPatchFile/TestClassPatch.php
  testData/actions/generation/generator/NewActionEntityGenerator/generateNewActionEntityFile/NewAction.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFile/AddTestAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php
  testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
  testData/actions/generation/generator/QueryModelGenerator/generateGetListQueryModelFile/GetListQuery.php
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php
  testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
  testData/actions/generation/generator/SaveEntityCommandGenerator/generateSaveEntityCommandFile/SaveCommand.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
Labels: Progress: review

#1261 Config Scope directory inspection
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/ModuleScopeInspection.html
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/ModuleScopeInspection.java
  testData/inspections/xml/ModuleScopeInspection/correctArea/app/code/Test/TestModule/etc/adminhtml/di.xml
  testData/inspections/xml/ModuleScopeInspection/correctArea/app/code/Test/TestModule/registration.php
  testData/inspections/xml/ModuleScopeInspection/incorrectArea/app/code/Test/TestModule/etc/adminhtmltypo/di.xml
  testData/inspections/xml/ModuleScopeInspection/incorrectArea/app/code/Test/TestModule/registration.php
  tests/com/magento/idea/magento2plugin/inspections/xml/ModuleScopeInspectionTest.java
Labels: Progress: review

#1259 EAV attributes code generators: Added default values of group property
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form
Labels: Progress: review

#1251 UCT custom coming versions
  src/com/magento/idea/magento2uct/execution/configurations/UctRunConfiguration.java
  src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.form
  src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.java
Labels: Progress: review

#1262 5.0.0 pre release
  CHANGELOG.md
  resources/icons/graphql.svg
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/MagentoIcons.java
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/context/xml/NewGraphQLSchemaAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/completion/provider/LayoutBlockCompletionContributor.java
  src/com/magento/idea/magento2plugin/completion/provider/LayoutContainerCompletionContributor.java
  src/com/magento/idea/magento2plugin/completion/provider/LayoutUpdateCompletionContributor.java
  src/com/magento/idea/magento2plugin/completion/provider/UiComponentCompletionProvider.java
  src/com/magento/idea/magento2plugin/completion/provider/VirtualTypeCompletionProvider.java
  src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
  src/com/magento/idea/magento2plugin/inspections/graphqls/SchemaResolverInspection.java
  src/com/magento/idea/magento2plugin/inspections/graphqls/fix/CreateResolverClassQuickFix.java
  src/com/magento/idea/magento2uct/execution/configurations/UctRunConfiguration.java
  src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.form
  src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.java
Labels: Progress: approved

#1266 1220: avoid indexing not existing plugin classes
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
Labels: Progress: approved

#1267 1220: fixed PluginIndex
  src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
Labels: Progress: ready for review

#1213 1206: Covered possible NullPointerException in InjectAViewModelDialog.java
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
Labels: Progress: approved

#1271 1269: fixed AWT events are not allowed inside write action
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
Labels: Progress: approved

#1272 1215: fix parsing of plugin sort order value [backport 5.0.1]
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
Labels: Progress: approved

#1273 1227: fix Create an entity - The translation function is not call on …
  CHANGELOG.md
  resources/fileTemplates/internal/Magento Form Button Block Class.php.ft
  testData/actions/generation/generator/FormButtonBlockGenerator/generateBackButtonBlock/MyBackButton.php
  testData/actions/generation/generator/FormButtonBlockGenerator/generateCustomButtonBlock/MyCustom.php
  testData/actions/generation/generator/FormButtonBlockGenerator/generateDeleteButtonBlock/DeleteBlock.php
  testData/actions/generation/generator/FormButtonBlockGenerator/generateSaveButtonBlock/SaveBlock.php
Labels: Progress: approved

#1214 1211: Changed configuration to update Intellij Plugin to the 1.5.2 ve…
  .gitattributes
  .github/workflows/gradle.yml
  build.gradle
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
  testData/actions/generation/generator/DeleteEntityGenerator/generateDeleteEntityFile/Delete.php
  testData/actions/generation/generator/WebApiInterfaceGenerator/withObjectTypesAndPhpDocComments/SimpleServiceTwoInterface.php
  testData/actions/generation/generator/WebApiInterfaceGenerator/withPrimitiveTypes/SimpleServiceInterface.php
  tests/com/magento/idea/magento2plugin/BaseProjectTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityCommandGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/FormButtonBlockGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGeneratorTest.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
  tests/com/magento/idea/magento2plugin/completion/BaseCompletionTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/graphqls/InspectionGraphqlsFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/inspections/xml/InspectionXmlFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/linemarker/LinemarkerFixtureTestCase.java
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
Labels: Progress: approved
