Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-01, with the labels that each got.

#909 899: lineMarkerXmltag Decorator#checkadd
  src/com/magento/idea/magento2plugin/linemarker/xml/LineMarkerXmlTagDecorator.java
Labels: Progress: approved

#917 Update 4 2 2 develop from 4 2 1 develop
  CHANGELOG.md
  build.gradle
  src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#910 900: Changed realization for function checkDelete using of CheckUtil.
  src/com/magento/idea/magento2plugin/linemarker/xml/LineMarkerXmlTagDecorator.java
Labels: Progress: approved

#921 Removed merge chance
  README.md
Labels: Progress: review

#927 907: Fix class cast exception
  src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#928 913: Fixed parse usage
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json
  testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved, Award: test coverage, Award: category of expertise

#930 619: Overriding layouts and templates allows to select an incompatibl…
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Award: special achievement, Progress: approved

#933 833: Added Open In Find Tool Window action to the Navigate to plugins linemarker
  src/com/magento/idea/magento2plugin/linemarker/SearchGutterIconNavigationHandler.java
  src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise

#934 932: Fixed general exception while accessing phpIndex.getAnyByFQN(classFQN)
  src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#935 620: Introduced custom search scope to exclude test files from search
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java
  src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
  src/com/magento/idea/magento2plugin/lang/roots/MagentoTestSourceFilter.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise

#936 853: Fix observer action visibility
  src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java
  src/com/magento/idea/magento2plugin/magento/files/Observer.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#937 276: Added uiComponent registration syntax highlighting as JSON
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/lang/injection/UiComponentSyntaxInjector.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, Award: category of expertise

#938 598: Added placeholder to dialog window
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/prompt/PlaceholderInitializerUtil.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Award: advanced, Progress: approved, Award: category of expertise

#939 Updated changelog for release 4.2.2
  CHANGELOG.md
Labels: partners-contribution, Partner: Atwix, Progress: approved
