Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-02, with the labels that each got.

#942 941: added integration enabled check for uiComponent
  src/com/magento/idea/magento2plugin/lang/injection/UiComponentSyntaxInjector.java
Labels: partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved

#944 943: added integration enabled check for custom search scope
  src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#948 Fixed style check
  src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
Labels: partners-contribution, Partner: Atwix, Progress: ready for review

#952 Added simple-json library to the project distribution
  CHANGELOG.md
  build.gradle
Labels: partners-contribution, Partner: Atwix, Progress: approved

#953 Update 4.3.0 from 4.2.3
  CHANGELOG.md
  build.gradle
Labels: partners-contribution, Partner: Atwix, Progress: approved

#956 955 add missing title to form
  src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#958 861: Developed context actions group, added generate routes.xml context action
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Routes XML.xml.ft
  resources/fileTemplates/internal/Magento Routes XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/context/xml/NewRoutesXmlAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/RoutesXmlGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateRoutesXml.java
  src/com/magento/idea/magento2plugin/magento/files/RoutesXml.java
  src/com/magento/idea/magento2plugin/magento/packages/ComponentType.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/RoutesXmlGeneratorTest.java
Labels: Award: complex, partners-contribution, Partner: Atwix, Progress: approved, Award: category of expertise

#962 966 add a placeholders to create new controller form
  resources/magento2/common.properties
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form
Labels: partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved

#970 961 add new context action for di.xmll file
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/context/xml/NewDiXmlAction.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#971 968: Added a new context dependent Action for the webapi.xml file generation
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/context/xml/NewWebapiXmlAction.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#969 965: Added a new context dependent Action for the acl.xml file generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento ACL XML.xml.ft
  src/com/magento/idea/magento2plugin/actions/context/xml/NewAclXmlAction.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#972 963: Bug during composer json generation
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#974 452: Added extended by references for the MFTF tests
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/indexes/IndexManager.java
  src/com/magento/idea/magento2plugin/reference/provider/mftf/TestExtendedByReferenceProvider.java
  src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
  src/com/magento/idea/magento2plugin/stubs/indexes/mftf/TestExtendsIndex.java
Labels: reference navigation, partners-contribution, Partner: Atwix, Award: special achievement, Progress: approved, QA passed

#976 975: Added a new context dependent Action for the config.xml file generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Config XML.xml.ft
  resources/fileTemplates/internal/Magento Config XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewConfigXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleConfigXmlFile.java
Labels: partners-contribution, Partner: Atwix, Award: special achievement, Progress: review

#983 980: Added widget.xml file in context generation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Widget XML.xml.ft
  resources/fileTemplates/internal/Magento Widget XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewWidgetXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleWidgetXmlFile.java
Labels: partners-contribution, Partner: Atwix, Progress: changes requested

#987 985: Added mview.xml file in context generation.
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Mview XML.xml.ft
  resources/fileTemplates/internal/Magento Mview XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewMviewXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleMviewXmlFile.java
Labels: partners-contribution, Partner: Atwix, Progress: review, Progress: on hold

#988 986: Added indexer.xml file in context generation.
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Indexer XML.xml.ft
  resources/fileTemplates/internal/Magento Indexer XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewIndexerXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleIndexerXmlFile.java
Labels: partners-contribution, Partner: Atwix, Progress: review, Progress: on hold

#990 989: Added view.xml file in context generation.
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento View XML.xml.ft
  resources/fileTemplates/internal/Magento View XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewViewXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleViewXmlFile.java
Labels: Progress: approved

#996 991: Added fieldset.xml file in context generation.
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Fieldset XML.xml.ft
  resources/fileTemplates/internal/Magento Fieldset XML.xml.html
  src/com/magento/idea/magento2plugin/actions/context/xml/NewFieldsetXmlAction.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleFieldsetXmlFile.java
Labels: partners-contribution, Partner: Atwix, Progress: approved, Progress: on hold

#583 Customer EAV attribute generation
  .github/workflows/gradle.yml
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft
  resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.html
  src/com/magento/idea/magento2plugin/actions/generation/NewCustomerEavAttributeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/CustomerEntityData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCustomerEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCustomerEavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/CustomerEavAttributePatchGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/AttributeMapperFactory.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/CategoryAttributeMapper.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/CustomerAttributeMapper.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/DefaultAttributeMapper.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java
  src/com/magento/idea/magento2plugin/magento/files/CustomerEavAttributeDataPatchFile.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeProperty.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/CustomerForm.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/DataPatchDependency.java
  src/com/magento/idea/magento2plugin/magento/packages/eav/EavEntity.java
  testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/CustomerAttributeSetupPatchGeneratorTest.java
Labels: partners-contribution, Partner: Atwix, Progress: changes requested

#998 993: Added email_templates.xml file in context generation.
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/context/xml/NewEmailTemplatesXmlAction.java
Labels: partners-contribution, Partner: Atwix, Progress: review, Progress: on hold

#1008 1006: Added placeholder to UI Component Grid dialog window
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1009 1007: Added placeholder to UI Component Form dialog window
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1005 959: Moving Example to the placeholder
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1018 1000: Fixed ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5(GetModuleNameByDirectoryUtil.java:47)
  src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: review

#1017 1012: Updating generating UI form Delete button
  src/com/magento/idea/magento2plugin/magento/packages/UiFormButtonTypeSettings.java
  testData/actions/generation/generator/FormButtonBlockGenerator/generateBackButtonBlock/MyBackButton.php
  testData/actions/generation/generator/FormButtonBlockGenerator/generateDeleteButtonBlock/DeleteBlock.php
  testData/actions/generation/generator/FormButtonBlockGenerator/generateSaveButtonBlock/SaveBlock.php
Labels: partners-contribution, Partner: Atwix, Progress: approved
