Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-09, with the labels that each got.

#1154 1152: Fix bug invalid file name: '26_Aug_2022_13:11:03-results.json'
  src/com/magento/idea/magento2uct/execution/output/ReportBuilder.java
Labels: Progress: approved

#1155 1141: Add code include, don't show generation action if readme exists
  resources/fileTemplates/includes/MD File Description.md.ft
  resources/fileTemplates/includes/MD File Description.md.html
  resources/fileTemplates/internal/Magento Module Readme File MD.md.ft
  src/com/magento/idea/magento2plugin/actions/context/md/NewReadmeMdAction.java
Labels: Progress: approved

#1153 1145: Removed content jumping from EAV generators forms
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCustomerEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java
Labels: Progress: review

#1157 1156: Fixed README.md template include is not working for project level
  src/com/magento/idea/magento2plugin/actions/context/CustomGeneratorContextAction.java
  src/com/magento/idea/magento2plugin/actions/context/md/NewReadmeMdAction.java
  src/com/magento/idea/magento2plugin/actions/context/util/GetTargetElementUtil.java
Labels: bug, Award: bug fix, Progress: approved

#1166 1102: Fix bug create an observer
  src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java
  src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
Labels: Progress: review

#1176 1100: Added inspection to check if type attr value in the virtual type tag exists
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/InvalidVirtualTypeSourceClassInspection.html
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/inspections/xml/InvalidVirtualTypeSourceClassInspection.java
Labels: Progress: approved

#1183 1180: Fixed ClassCastException
  src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
Labels: Progress: review

#1186 1143 fix NullPointerException at ObserverDeclarationInspection Class
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Labels: Progress: approved

#1181 1144: Add checks and detailed error messages during plugin activation
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Labels: Progress: approved

#1187 Revert "Fixed new intellij version compatibility issues"
  build.gradle
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
Labels: Progress: ready for review

#1147 4.4.0 pre release
  CHANGELOG.md
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java
  src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoComponentManager.java
  src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Labels: Progress: review

#1190 Reverting raw code from the 5.0.0-develop
  build.gradle
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
Labels: Progress: approved

#1191 Update 5.0.0 develop from 4.4.0 develop
  CHANGELOG.md
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
  src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java
  src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
  src/com/magento/idea/magento2plugin/magento/packages/MagentoComponentManager.java
  src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java
  src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
  src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Labels: Progress: approved

#1193 1179: moved graphql dependent actions to the withJsGraphQl.xml config…
  resources/META-INF/plugin.xml
  resources/META-INF/withJsGraphQl.xml
Labels: Progress: approved

#1192 1135: Fixed issues with incorrect generation of resolver class
  CHANGELOG.md
  resources/magento2/inspection.properties
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
  src/com/magento/idea/magento2plugin/inspections/graphqls/SchemaResolverInspection.java
  src/com/magento/idea/magento2plugin/inspections/graphqls/fix/CreateResolverClassQuickFix.java
Labels: Progress: approved

#1189 1175: Add action to generate events.xml file through the context menu
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/context/xml/NewEventsXmlAction.java
Labels: Progress: approved

#1199 Merge 4.4.0 develop into 5.0.0 develop
  resources/META-INF/plugin.xml
  resources/META-INF/withJsGraphQl.xml
  resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft
  testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
Labels: Progress: review

#1200 1139: Creating a new observer template
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Observer File.php.ft
  resources/fileTemplates/internal/Magento Module Observer File.php.html
  src/com/magento/idea/magento2plugin/actions/context/php/NewObserverAction.java
  src/com/magento/idea/magento2plugin/actions/generation/ModuleObserverData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleObserverGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleObserverFile.java
  testData/actions/generation/generator/ModuleObserverGenerator/generateModuleObserverFile/TestClassObserver.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleObserverGeneratorTest.java
Labels: Progress: approved

#1201 1195: Changed Magento icons to GraphQL icons for GraphQL related actions
  resources/icons/graphql.svg
  src/com/magento/idea/magento2plugin/MagentoIcons.java
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/context/xml/NewGraphQLSchemaAction.java
  src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java
Labels: Progress: approved

#1188 1139: Creating a new data patch template
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Setup Patch File.php.ft
  resources/fileTemplates/internal/Magento Module Setup Patch File.php.html
  src/com/magento/idea/magento2plugin/actions/context/php/NewSetupDataPatchAction.java
  src/com/magento/idea/magento2plugin/actions/generation/ModuleSetupDataPatchData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewSetupDataPatchDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewSetupDataPatchDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleSetupDataPatchGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleSetupDataPatchFile.java
  testData/actions/generation/generator/ModuleSetupDataPatchGenerator/generateModuleSetupDataPatchFile/TestClassPatch.php
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleSetupDataPatchGeneratorTest.java
Labels: Progress: approved

#1202 1171: Override template in a module
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/OverrideFileAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideLayoutInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInModuleAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInModuleGenerator.java
Labels: Progress: approved
