Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-03, with the labels that each got.

#1024 1023: Added an additional path field for UCT configuration dialog (to cover theme folder scanning)
  src/com/magento/idea/magento2uct/settings/UctSettingsService.java
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.form
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1020 414: Added Images support for Copy Magento Path
  src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1027 409: Added argument injection/replacement action
  resources/META-INF/plugin.xml
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/generation/InjectConstructorArgumentAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/xml/DiArgumentData.java
  src/com/magento/idea/magento2plugin/actions/generation/data/xml/DiArrayValueData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/GatherArrayValuesDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/GatherArrayValuesDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewArgumentInjectionDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewArgumentInjectionDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/ExtendedNumericRule.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/ArgumentInjectionGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/code/util/DiXmlTagManipulatorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/CommitXmlFileUtil.java
  src/com/magento/idea/magento2plugin/magento/packages/DiArgumentType.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/php/PhpPsiElementsUtil.java
  src/com/magento/idea/magento2plugin/util/php/PhpTypeMetadataParserUtil.java
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectArrayValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectBooleanValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectConstValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectInitParameterValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectNestedArrayValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectNullValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectNumberValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectObjectValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/injectStringValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/replaceObjectValueWithFactoryValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/replaceObjectValueWithNullValue/di.xml
  testData/actions/generation/generator/ArgumentInjectionGenerator/replaceObjectValueWithProxyValue/di.xml
  testData/project/magento2/app/code/Foo/Bar/etc/crontab/di.xml
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ArgumentInjectionGeneratorTest.java
Labels: partners-contribution, Partner: Atwix, Award: advanced, Progress: approved, Award: category of expertise

#1021 967 add context action to create layout xml file
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Layout XML.xml.ft
  resources/magento2/common.properties
  resources/magento2/validation.properties
  src/com/magento/idea/magento2plugin/actions/context/xml/NewLayoutXmlAction.java
  src/com/magento/idea/magento2plugin/actions/generation/data/LayoutXmlData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewLayoutTemplateDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewLayoutTemplateDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/util/DialogFieldErrorUtil.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/LayoutNameRule.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/LayoutXmlTemplateGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateLayoutXml.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1015 828: rename inspection titles
  resources/inspectionDescriptions/CallingDeprecatedMethod.html
  resources/inspectionDescriptions/ExtendingDeprecatedClass.html
  resources/inspectionDescriptions/ImplementedDeprecatedInterface.html
  resources/inspectionDescriptions/ImportingDeprecatedClass.html
  resources/inspectionDescriptions/ImportingDeprecatedInterface.html
  resources/inspectionDescriptions/InheritedDeprecatedInterface.html
  resources/inspectionDescriptions/OverridingDeprecatedConstant.html
  resources/inspectionDescriptions/OverridingDeprecatedProperty.html
  resources/inspectionDescriptions/UsingDeprecatedClass.html
  resources/inspectionDescriptions/UsingDeprecatedConstant.html
  resources/inspectionDescriptions/UsingDeprecatedInterface.html
  resources/inspectionDescriptions/UsingDeprecatedProperty.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
  src/com/magento/idea/magento2uct/execution/output/UctReportOutputUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: review

#1022 1011: Updated docblock for code generator
  resources/fileTemplates/internal/Magento CLI Command Class.php.ft
  resources/fileTemplates/internal/Magento Collection Class.php.ft
  resources/fileTemplates/internal/Magento Data Model.php.ft
  resources/fileTemplates/internal/Magento Entity Search Results.php.ft
  resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.ft
  resources/fileTemplates/internal/Magento Model Class.php.ft
  resources/fileTemplates/internal/Magento Resource Model Class.php.ft
  resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
  testData/actions/generation/generator/CLICommandClassGenerator/generateCLICommandClass/TestCLICommandPHPClass.php
  testData/actions/generation/generator/DataModelGenerator/generateDataModel/Sample.php
  testData/actions/generation/generator/DataModelGenerator/generateDataModelWithoutInterface/Sample.php
  testData/actions/generation/generator/GridActionColumnFileGenerator/generateGridActionColumnFile/BookBlockActions.php
  testData/actions/generation/generator/ModuleCollectionGenerator/generateFile/TestCollection.php
  testData/actions/generation/generator/ModuleCollectionGenerator/generateWithTheSameNamesForResourceModelAndModel/Collection.php
  testData/actions/generation/generator/ModuleModelGenerator/generateFile/TestModel.php
  testData/actions/generation/generator/ModuleModelGenerator/generateWithTheSameNameForResourceModel/Test.php
  testData/actions/generation/generator/ModuleResourceModelGenerator/generateFile/TestResourceModel.php
  testData/actions/generation/generator/ModuleResourceModelGenerator/generateFileWithDtoReference/TestResourceModel.php
  testData/actions/generation/generator/SearchResultsFilesGenerator/generateSearchResultsFile/BookSearchResults.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php
  testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1029 Mainline/UCT-1023: Theme scanning feature
  src/com/magento/idea/magento2plugin/magento/packages/ComponentType.java
  src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
  src/com/magento/idea/magento2uct/execution/output/ReportBuilder.java
  src/com/magento/idea/magento2uct/execution/output/Summary.java
  src/com/magento/idea/magento2uct/execution/output/UctReportOutputUtil.java
  src/com/magento/idea/magento2uct/execution/scanner/ModuleScanner.java
  src/com/magento/idea/magento2uct/execution/scanner/data/ComponentData.java
  src/com/magento/idea/magento2uct/inspections/UctInspectionManager.java
  src/com/magento/idea/magento2uct/settings/UctSettingsService.java
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.form
  src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1032 613: Added possibility to compare overridden template with the original one
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/comparator/CompareTemplateAction.java
  src/com/magento/idea/magento2plugin/actions/comparator/util/DiffRequestChainUtil.java
  src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
  src/com/magento/idea/magento2plugin/util/magento/area/AreaResolverUtil.java
Labels: Progress: review, Award: category of expertise

#1036 Change overwrite templates feature for action menu
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/actions/generation/OverrideFileInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideLayoutInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideLayoutInTheme.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideLayoutInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideLayoutInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInThemeGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1037 1031: Remove deprecated FilenameIndex#getVirtualFilesByName method usage
  src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
Labels: partners-contribution, Partner: Atwix, Progress: review

#1044 984: Filtered generated folder from reference resolving results
  resources/META-INF/plugin.xml
  src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1043 1035: removed deprecated Function#getReturnType
  src/com/magento/idea/magento2plugin/actions/generation/util/FillTextBufferWithPluginMethods.java
Labels: partners-contribution, Partner: Atwix, Progress: review, Progress: on hold

#1046 Fixes for overrite for js and css files in theme
  resources/fileTemplates/internal/Require Config JS File.js.ft
  resources/fileTemplates/internal/Require Config JS File.js.html
  src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInThemeGenerator.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/js/RequireJsConfigGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/RequireConfigJsFile.java
  src/com/magento/idea/magento2plugin/magento/packages/OverridableFileType.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1047 Fixed Magento installation path suggestion
  resources/META-INF/pluginIcon.svg
  src/com/magento/idea/magento2plugin/project/SettingsForm.java
Labels: Progress: approved

#1045 614: Provided file path references for JS:STRING_LITERAL psi elements in the js files
  src/com/magento/idea/magento2plugin/reference/js/JsReferenceContributor.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  testData/reference/js/RequireJsReferenceRegistrar/filePathInMixinDeclarationMustHaveReference/requirejs-config.js
  tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
  tests/com/magento/idea/magento2plugin/reference/js/RequireJsReferenceRegistrarTest.java
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1038 UCT-1030: Added configuration files support
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/UsedDeprecatedConstantInConfig.html
  resources/inspectionDescriptions/UsedDeprecatedMethodInConfig.html
  resources/inspectionDescriptions/UsedDeprecatedTypeInConfig.html
  resources/inspectionDescriptions/UsedNonExistentConstantInConfig.html
  resources/inspectionDescriptions/UsedNonExistentMethodInConfig.html
  resources/inspectionDescriptions/UsedNonExistentTypeInConfig.html
  resources/uct/bundle/inspection.properties
  src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
  src/com/magento/idea/magento2uct/execution/scanner/ModuleFilesScanner.java
  src/com/magento/idea/magento2uct/inspections/UctInspectionManager.java
  src/com/magento/idea/magento2uct/inspections/UctProblemsHolder.java
  src/com/magento/idea/magento2uct/inspections/xml/ModuleConfigFileInspection.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedDeprecatedConstantInConfig.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedDeprecatedMethodInConfig.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedDeprecatedTypeInConfig.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedNonExistentConstantInConfig.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedNonExistentMethodInConfig.java
  src/com/magento/idea/magento2uct/inspections/xml/UsedNonExistentTypeInConfig.java
  src/com/magento/idea/magento2uct/packages/SupportedIssue.java
  src/com/magento/idea/magento2uct/util/php/MagentoReferenceUtil.java
  src/com/magento/idea/magento2uct/util/php/MagentoTypeEscapeUtil.java
  src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
  src/com/magento/idea/magento2uct/versioning/indexes/data/ExistenceStateIndex.java
Labels: partners-contribution, Partner: Atwix, Progress: approved
