Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-06, with the labels that each got.

#1114 1094 fix a new layout action error
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewLayoutTemplateDialog.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
Labels: partners-contribution, Partner: Atwix, Progress: review, Progress: on hold

#1117 1113: Fixed IllegalArgumentException: Argument for @NotNull parameter 'dataKey' must not be null in CompareTemplateAction
  src/com/magento/idea/magento2plugin/actions/comparator/CompareTemplateAction.java
Labels: bug, partners-contribution, Partner: Atwix

#1110 1016: Add optional generation of README.md during module creation
  resources/META-INF/plugin.xml
  resources/fileTemplates/internal/Magento Module Readme File MD.md.ft
  resources/fileTemplates/internal/Magento Module Readme File MD.md.html
  src/com/magento/idea/magento2plugin/actions/generation/data/ModuleReadmeMdData.java
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form
  src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
  src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleReadmeMdGenerator.java
  src/com/magento/idea/magento2plugin/magento/files/ModuleReadmeMdFile.java
  testData/actions/generation/generator/ModuleReadmeMdGenerator/generateModuleReadmeMdFile/README.md
  tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
  tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleReadmeMdGeneratorTest.java
Labels: partners-contribution, Partner: Atwix, Progress: on hold
