Repository magento/magento2-phpstorm-plugin, pull requests merged in 2022-04, with the labels that each got.

#1056 4.3.0 develop forwardport
  CHANGELOG.md
Labels: Progress: ready for review

#1063 1048: Fixed bug with wrong text range
  src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#1062 1058: Fixed bug with the file separator on windows
  src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix

#1064 1010: Fixed module context actions available in the theme
  src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
  src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
  src/com/magento/idea/magento2plugin/util/RegExUtil.java
  src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#1065 1050: added raw plugin verifier configuration
  build.gradle
Labels: partners-contribution, Partner: Atwix, Progress: approved

#1080 1049: fixed index already disposed in search
  src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java
  src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#1081 1051 fix already disposed exception
  src/com/magento/idea/magento2plugin/magento/packages/MagentoComponentManager.java
Labels: partners-contribution, Partner: Atwix, Award: bug fix, Progress: approved

#1082 Preparing release 4.3.1
  CHANGELOG.md
Labels: partners-contribution, Partner: Atwix, Progress: approved
